### ISSUE TITLE
EKA2L1 expects the folder ROM is in to be in uppercase but it's created in lowercase

### ISSUE THREAD

**Issue by Exploder98** [EKA2L1/EKA2L1#102]
When the ROM is copied, the folder is named in lowercase (example: `/path/to/data/roms/rm-356`). However, the firmware code is saved in uppercase and when loading the rom EKA2L1 expects the folder name to be in uppecase (`RM-356`). This could be fixed by either saving the firmware code in lowercase ([here](https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/manager/src/rpkg.cpp#L354)) or by converting it to lowercase while loading the ROM ([here](https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/console/src/state.cpp#L82)).

**Comment by pent0** [comment]
Confirmed by @Exploder98 to fixed in Discord. Thanks a lot!
