### ISSUE TITLE
EKA2L1 converts the whole path to lowercase when loading some files

### ISSUE THREAD

**Issue by Exploder98** [EKA2L1/EKA2L1#103]
The whole path is converted to lowercase in [vfs.cpp](https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/epoc/src/vfs.cpp#L538). This means that data folder paths with uppercase letters will not work. Only `vert_path_copy` should be converted to lowercase.

**Comment by pent0** [comment]
Confirmed by @Exploder98 to fixed in Discord. Thanks a lot!
