### ISSUE TITLE
BLAZ3D Deadlock

### ISSUE THREAD

**Issue by UroshUchiha** [EKA2L1/EKA2L1#106]
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4535100/EKA2L1.log)
[Screenshot](https://cdn.discordapp.com/attachments/456011763713048588/703628330225631312/unknown.png)

BLAZ3D Deadlocks
Log filtered for Unimplemented. No 'Panic' in the log

**Comment by pent0** [comment]
Confirmed same reason of froze as The Sims 3 while trying to establish telephony connection

**Comment by TRR95** [comment]
> Confirmed same reason of froze as The Sims 3 while trying to establish telephony connection
