### ISSUE TITLE
Duke3D (Deadlock)

### ISSUE THREAD

**Issue by UroshUchiha** [EKA2L1/EKA2L1#113]
![image](https://user-images.githubusercontent.com/36758864/80693499-62e30880-8ad3-11ea-962f-2c253de330df.png)
This is the only thing that appears before the threads go into waiting mode
![image](https://user-images.githubusercontent.com/36758864/80693605-90c84d00-8ad3-11ea-86bd-4dcef34a66a2.png)

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4557298/EKA2L1.log)

**Comment by pent0** [comment]
Missing system call 0x21, app terminates pending (-1003 error code at the end)

**Comment by pent0** [comment]
Missing game files confirmed, not emulator issue
