### ISSUE TITLE
Game running too fast

### ISSUE THREAD

**Issue by NuruTasDemir** [EKA2L1/EKA2L1#115]
Golf Pro is working on E5-00 ROM, but speed is very fast, even if Refresh Rate set to 15
![image](https://user-images.githubusercontent.com/49725539/80917523-9a221580-8d70-11ea-934d-f597609a4a37.png)

**Comment by pent0** [comment]
Carmageddon also runs too fast, tied to CPU speed. TODO is allow user changing speed dynamically

![image](https://media.discordapp.net/attachments/703563521379663883/706094341524815923/unknown.png)

**Comment by pent0** [comment]
Lock'n Load 2 also has this problem, a person on Discord reported
[Log](https://github.com/EKA2L1/EKA2L1/files/4574267/message.1.txt)

**Comment by pent0** [comment]
Fixed with host timing
