### ISSUE TITLE
[Deadlocks] Alchemy Classic

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#118]
Stuck at a "panic thread", there isn't even window showing it at least trying to render.

SIS Name: Alchemy classic (360x640. S60 5th Edition (Symbian^3))
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4579194/EKA2L1.log)

**Comment by pent0** [comment]
You have not installed Qt for this app, and QT installation is not yet supported!
