### ISSUE TITLE
[Deadlocks] The Sims 2 Pets

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#125]
The Sims 2 Pets Deadlocks. I've used notepad++ to search for QT or Python and it found nothing  

SIS Name: The Sims 2 Pets (OS 9.1)
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4591287/EKA2L1.log)

**Comment by pent0** [comment]
Turn off all the log cpu options next time. Its used for extend debugging when something cant be seen on surface.

This looks like a ngage 2.0 game.
