### ISSUE TITLE
[Menus] C-Dogs (Cyber Dogs)

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#128]
C-Dogs gets to the main menu. the good news is the sound works. The bad news is selecting anything with the white square  makes the screen go black

SISX Name: C-Dogs (Symbian (9.1, 9.2, 9.3, 9.4). S60 5th (Symbian^1))
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4597300/EKA2L1.log)

**Comment by pent0** [comment]
This game died (thread panic) when clicking the white square (see in the log). Looks like:

> E { eka2l1::fbscli::fetch: Unhandled FBScli opcode 0x22 }

Maybe the direct cause
