### ISSUE TITLE
[Deadlock] Crystal Mountain

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#134]
Many errors with this one

Name: Crystal mountain (Symbian (9.1, 9.2, 9.3, 9.4). S60 5th Edition (Symbian^1))
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4598633/EKA2L1.log)

**Comment by pent0** [comment]
HAL get display mode not implemented
Plus
> E { eka2l1::epoc::window_group::execute_command: Unimplemented window group opcode 0x77! }
