### ISSUE TITLE
Corrupted reflections in Asphalt 2 HD

### ISSUE THREAD

**Issue by stranno** [EKA2L1/EKA2L1#145]
Reflections get corrupted once you exit a tunnel. Neon lights under the car could be also wrong, I'm not sure.

Controls get crazy sometimes, but that happens with other games (Brother in Arms) iirc.

https://streamable.com/d9364g

https://gofile.io/d/0VjyuQ

**Comment by TRR95** [comment]
Please you post this here instead: https://github.com/EKA2L1/Compatibility-List
