### ISSUE TITLE
More Research Is Needed List

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#150]
This is list of things that need to be researched 

- [x] Can EKA2L1 run apps made using NS Basic?
- [x] Can EKA2L1 run apps made using  Ruby?
- [ ] Can EKA2L1 run apps made using  .NET?
- [ ] Can EKA2L1 run apps made using Web Runtime (WRT)?
- [x] Can EKA2L1 run apps made using  Standard C/C++?

- [ ] **MOAP(S) and OPP(S)**

Both a UI and software middleware that ran on top of Symbian OS. It was only available in Japan on devices sold by the telecommunications company, NTT Docomo as part of their [FOMA brand](https://en.wikipedia.org/wiki/Freedom_of_Mobile_Multimedia_Access)

Despite a large amount of Japanese devices (and at least one Taiwanese device) using these two platforms (mainly do to NTT Docomo being a dominant phone carrier in Japan) I can't find much info or software that ran on this platform, so more research is needed and getting MOAP(S) or OPP(S) device would be a good first step.

**Comment by Pranay0302** [comment]
MOAP(S) platform from carrier NTT DoCoMo in the Japanese market is an interface.
OPP(s) is Operator Pack Symbian is the successor of MOAP.

Symbian is a discontinued mobile operating system (OS) and computing platform designed for smartphones.

- Symbian OS works on Standard C/C++, We can write  C++ code on EKA2L1, So EKAL21 can run apps made by using standard C/C++.

- EKA2L1 is designed for Visual Basic programmers who can use NS Basic to develop apps for S60 3rd Edition and UIQ 3 devices.

- EKA2L1 can also run the apps made by Ruby as it is also is compatible with UIQ3.0 and S60 third edition.

- I wasn't able to gather much information about .net and WRT, When i'll learn something about it, i'll definitely look forward to share the information.

**Comment by TRR95** [comment]
> MOAP(S) platform from carrier NTT DoCoMo in the Japanese market is an interface.
> OPP(s) is Operator Pack Symbian is the successor of MOAP.

> * I wasn't able to gather much information about .net and WRT, When i'll learn something about it, i'll definitely look forward to share the information.

Thanks for the research. the big question when it comes to MOAP(S) and OPP(S) is i-mode. from when i can tell, these two interfaces can run games/software made with i-mode Java but I can't confirm this.
