### ISSUE TITLE
Option to separate the display window

### ISSUE THREAD

**Issue by stranno** [EKA2L1/EKA2L1#151]
I would like an option to separate (in an unique window) the display window (Screen 0) from the EKA2L1 main window (menu).

That would allow capture software like OBS to capture directly the game display, instead of the EKA2L1 full frame, reducing the transformations in the capture pipeline (you would not need to crop the full frame).

![Z3UtsHq](https://user-images.githubusercontent.com/6293197/82949584-2b695e00-9fa4-11ea-8c11-7a07e524c72e.png)

**Comment by pent0** [comment]
Fixed with c95b2068b04b4deeb6646a24a66b3851d9114171
