### ISSUE TITLE
[Crash] Installing Angry Birds

### ISSUE THREAD

**Issue by AlanixWhames** [EKA2L1/EKA2L1#153]
Game: Angry Birds
OS used: S60v5 & S60v3 (5800 Xpressmusic and N95)
Report: This game crashes the emulator when install it's package.
Log: [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4692373/EKA2L1.log)
PC Characters: Lenovo ideapad Win10, 4gb Ram, Intel Pentium Gold.

**Comment by TRR95** [comment]
@AlanixWhames post all you game tests on the Compatibility List. https://github.com/EKA2L1/Compatibility-List/issues
