### ISSUE TITLE
Closed :) 

### ISSUE THREAD

**Issue by AlanixWhames** [EKA2L1/EKA2L1#156]

**Comment by pent0** [comment]
Hi, if I reproduce this correctly you are trying to install another device after just installed another one right? I see that this ROM has no problem installing, just that if you try to install many in one instance it will not work. 

I will fix my side issue, but I just want to get more information about yours.

**Comment by pent0** [comment]
Please check this build https://github.com/EKA2L1/EKA2L1/commit/623e375d707cba59ed7d47b14bc66beeb916a622

Click on the V/X and choose appveyor, download as usual

**Comment by AlanixWhames** [comment]
Thanks you bent, but i installed the rom in a one instance without devices

**Comment by pent0** [comment]
Yes, thank you for your information. If possible please retest with the link I give you above. Thanks a lot.

**Comment by AlanixWhames** [comment]
Thanks to you bent :)

**Comment by pent0** [comment]
Discussed with the author of this issue and this can't be reproduce. Close until then.
