### ISSUE TITLE
Ideaworks Renderer: T-Pages Error

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#162]
A common error for a lot of games is the "Out of T-Page" error, finding a way to fix this is needed.
![82715934-6a20b080-9c52-11ea-8ff9-fa2093d3141e](https://user-images.githubusercontent.com/49062935/84472290-30850900-ac44-11ea-8e53-b1e14492f455.png)

**Comment by Redill603** [comment]
from what i know this hppens when the game doesn't detect hw acceleration, like on nokia 500

**Comment by pent0** [comment]
To solve this, need to implement #51 and the DLL set comes with GLES (OOM DLL for eg.)

**Comment by TRR95** [comment]
My post is redundant as this will be fixed when GLES library hook is added
