### ISSUE TITLE
Linux builds missed

### ISSUE THREAD

**Issue by Symbian9** [EKA2L1/EKA2L1#165]
GDrive folder is empty:

- https://drive.google.com/open?id=1nXNL1n7hKX05JzF25u6pHAXP-VrV2EX9

Could you upload Linux builds to *Bintray* (https://bintray) instead?

- [ ] https://bintray.com/EKA2L1/EKA2L1
  - [ ] https://dl.bintray.com/EKA2L1/EKA2L1

### REFERENCE

- https://github.com/bpicode/github-action-upload-bintray
- https://github.com/hpcsc/upload-bintray-docker-action
- https://github.com/daviderestivo/travis-emacs-head-bottle
- https://github.com/wanduow/action-bintray-upload-rpm-packages

**Comment by pent0** [comment]
So sorry for the late reply! I will try to do so, and report to you when it's done.

**Comment by pent0** [comment]
Fixed with new Github Actions CI.
