### ISSUE TITLE
Based on the behaviour of EKA1 and EKA2 

### ISSUE THREAD

**Issue by Pranay0302** [EKA2L1/EKA2L1#166]
Had a problem in understanding the **Symbian OS internals**, its architecture basically.

**Comment by pent0** [comment]
This is a question?

**Comment by Pranay0302** [comment]
Can someone send me a manual or some details about the Symbian OS internals

**Comment by pent0** [comment]
Our discord has documents, get on it

**Comment by Pranay0302** [comment]
roger that
