### ISSUE TITLE
Disappearing Apps

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#167]
A lot of apps never show up on the app list after getting installed, even closing EKA2L1 and starting it up again won't show these apps. this happens across all versions Symbian OS although it seems to happen the most with S60v1 apps. No logs can be given as you can't run the apps and there are no errors during the installation progress.

Because this effects playability, testing, and the development of the emulator, this is a critical issue that needs to be prioritized.

**Comment by pent0** [comment]
Diagnosis: 
- With s60v1 apps, apps registeration files is in another folder and has different structure layout. I will look onto it in the future. TODO
- With apps from EKA2 and upper, this does happen. You can work around by running eka2l1 with console line arguments --app "<virtual_path_to_exe>", but this also needs to be looked into.

Thank you for reporting this issue.

**Comment by pent0** [comment]
S60v1 app displays are mostly fixed now.
