### ISSUE TITLE
where can i find a rpkg file? and what is rpkg file

### ISSUE THREAD

**Issue by BeatMicrosoft** [EKA2L1/EKA2L1#171]
I am newer, I had built succeed.i have the eka2l1.exe file , when I run , it needs rpkg file?  but what is rpkg file? and how do I provide it
I want to run Symbian os on it. but I don't know how to do it. (I built eka2l1.exe)
.thanks

**Comment by pent0** [comment]
We instruct you to go on wiki, go see the wiki please: https://github.com/EKA2L1/EKA2L1/wiki/Dumping-the-ROM-and-ROFS
