### ISSUE TITLE
Overlapping SVC call numbers between 9.3 and 9.4?

### ISSUE THREAD

**Issue by agatti** [EKA2L1/EKA2L1#175]
Hi there,

I'm adding the `ProcessOpenById` SVC call which on my ROM seems to have SVC code 0x72 (and in fact it's missing in `svc_register_funcs_v94`).  When looking at the SVC maps for the various 9.x OS versions to add that SVC for those as well I noticed that v9.3 has SVC calls starting from `thread_kill` being off by one.  As in, SVC call 0x72 that is missing in v9.4 is mapped to `thread_kill` on v9.3, but on v9.4 `thread_kill` is 0x73.

I'm not sure if that's a mistake or not, because `RProcess.Open(TProcessId, TOwnerType)` has been in since pretty much forever.

Since I have no v9.3 ROMs, I cannot really test this - is it a bug? :)

**Comment by pent0** [comment]
Some svc calls are added and removed, so there is sometimes it ordinal differs from newer os. We reversed well and things are running well (discord has some s60v3 games running well with it). No worries.

**Comment by pent0** [comment]
I guess I can close this? Feel free to chat or continue discussion.
