### ISSUE TITLE
Help with EKA2L1

### ISSUE THREAD

**Issue by Ink321** [EKA2L1/EKA2L1#181]
The last video showed that the Lament Island game is running on the emulator, how to do it? My game does not see the folder with files, neither on disk e, nor in system \ app

**Comment by pent0** [comment]
Since the game server is down, you must
- Preprare a device installed (5320 is recommended, s60v3)
- Simlife game files. Put them in data storage path\drives\e\.

Just search on internet. If you have problem afterwards give me the log, thanks

**Comment by Ink321** [comment]
[EKA2L1.zip](https://github.com/EKA2L1/EKA2L1/files/5179948/EKA2L1.zip)
Using smartphone image 5320
I put the files on the path \ drives \ e \ Simlife
I did everything as in the instructions from the Internet, on the smartphone the game starts in this way, and on the emulator it only says that the folder with the files was not found. I attach the log.

**Comment by Ink321** [comment]
A shadow warrior game that has a similar installation method works, but I don't understand how to set up controls in it.

**Comment by pent0** [comment]
Can you show me screenshot of your folder layout. Also if possible please move files to drives\e\simlife\island\. Game will look there directly

**Comment by pent0** [comment]
![image](https://user-images.githubusercontent.com/25717050/92333031-5b98c080-f0ac-11ea-9dd7-becad17c5196.png)
My layout for example for this game

**Comment by Ink321** [comment]
I made the folder structure as you said, but the game still does not start and the logger began to record some new errors. Log file and screenshot in the archive. The image of the smartphone was taken here https://mega.nz/folder/v2ojCDSJ#4pf2QMop50TwJo8L1iczJA
[EKA2L1.zip](https://github.com/EKA2L1/EKA2L1/files/5180181/EKA2L1.zip)

**Comment by pent0** [comment]
Resolved on Discord
