### ISSUE TITLE
Windows 10 2004 cannot run

### ISSUE THREAD

**Issue by Yebanqingkong** [EKA2L1/EKA2L1#185]
![2020-09-15_150036](https://user-images.githubusercontent.com/71312014/93176717-4256da80-f764-11ea-839a-9262917df5cc.png)
Hello, first of all thank you for making a simulator for the Symbian system. I am very happy to have the opportunity to remember my youth. But currently I have encountered a problem. I cannot open the main program running EKA2L1. The result of running an error is shown in the figure. My system is Windows 10 2004. Please tell me how to solve it, thank you.

**Comment by TRR95** [comment]
before I make you wait for Bent to comment, I'm going to ask you to check Windows Update, there is a weird issue were WU will brake EKA2L1 if there is an update available it wants you download.

**Comment by pent0** [comment]
Hi, there are some limitations:
- You need OpenGL 3.3 or newer to use this emulator. Search Google or Baidu on how to check
- Your path must not contain Unicode character. Means no Chinese characters.

If you have checked these I will look at it again, thank you.

**Comment by Yebanqingkong** [comment]
> Hi, there are some limitations:
> 
> * You need OpenGL 3.3 or newer to use this emulator. Search Google or Baidu on how to check
> * Your path must not contain Unicode character. Means no Chinese characters.
> 
> If you have checked these I will look at it again, thank you.

![2020-09-15_231713](https://user-images.githubusercontent.com/71312014/93229950-ba93bf00-f7a9-11ea-8332-c5939aabf1de.png)
Thank you for your answer, indeed, it is because my computer runs on the core display by default, and my core supports up to 3.1, so it cannot run. But when I changed to independent display, the problem was solved.

**Comment by pent0** [comment]
Thanks for cooperating. I will close this. If you have more problems please open another separate issue
