### ISSUE TITLE
N-Gage: Notifier Server 0x2 & 0x3

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#191]
Many games are braking because Notifier Server opcode 0x2 and or 0x3 are unimplemented.

### **List of Games that need Opcode 0x2 and or 0x3**

- Warhammer 40,000: Glory in Death
- Atari Masterpieces Vol. II
- Atari Masterpieces Vol. I
- Rifts: Promise Of Power
- Asphalt Urban GT 2
- X-Men Legends II
- Mile High Pinball
- Spiderman 2
- Xanadu Next
- Glimmerati
- Civilazation
- High Seize

**Comment by pent0** [comment]
They are used to print error messages and are stubbed. Yep implementing them is a need, but we might as well see what error caused them to be called
