### ISSUE TITLE
SMS verification in the game

### ISSUE THREAD

**Issue by 1755917579** [EKA2L1/EKA2L1#194]
Hello, I am an ordinary player in China. I like this software very much. I just want to play a domestic game when I was a teenager. Its name is "7days", and its Chinese name is "Seven Nights". It is Chengdu dingguo make。This game can be played on this software, but the game needs to send short message to buy the plot. The game ROM is a cracked version and does not need to be sent out. However, when the SMS sending interface pops up, you can't click to confirm sending. How can I solve this problem. thank you. I'm sorry, I don't know much English. I use the translation software. I hope you can understand what I mean.
![QQ图片20200926014207](https://user-images.githubusercontent.com/71896558/94298954-8aae9d80-ff99-11ea-84e4-ec0074bd3624.png)

**Comment by pent0** [comment]
Yes, sorry. This is a well known issue. But we have not resolved yet. Please wait for more informations. We also got the hand on this version

**Comment by pent0** [comment]
Fixed in 845425331e5edce2724b17aec7e4aa6d1fd0cbee. Please test

**Comment by 1755917579** [comment]
Sorry, I don't quite follow you. What are these Numbers for?

**Comment by stranno** [comment]
> Sorry, I don't quite follow you. What are these Numbers for?

https://github.com/EKA2L1/EKA2L1/actions/runs/272994475

This.

**Comment by 1755917579** [comment]
Thank you. Hahaha, the problem is solved.
![QQ图片20200926051015](https://user-images.githubusercontent.com/71896558/94316404-db80bf00-ffb6-11ea-8e11-264c7dfe0731.png)

**Comment by pent0** [comment]
I hope you enjoy the game. Thabk you for reporting this issue, gonna close it!
