### ISSUE TITLE
N-Gage: System call: 0x80007D! / 0x80007E

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#196]
The award for Thread Killing the most games goes to "0x80007D! & 0x80007E" this is an issue with 15 games and both calls need to be added

### **List of Games that need system call: 0x80007D! & 0x80007E**

- Tom Clancy's Splinter Cell
- Marcel Desailly Pro Soccer
- Barakel : The Fallen Angel
- The Roots: Gates of Chaos
- SSX: Out of Bounds
- Operation Shadow
- N-Gage Freestyle
- Stuntcar Extreme
- Requiem of Hell
- Pool Friction
- Virtua Tennis
- Red Faction
- TechWars
- Moto GP
- Sango

**Comment by pent0** [comment]
Fixed in 17ca10bd13cbf4d891504249b8669a4ce793a60f. Game working depends on other issues
