### ISSUE TITLE
How to get ROM

### ISSUE THREAD

**Issue by xiaodong97** [EKA2L1/EKA2L1#197]
I don't know how to get ROM, what I get with rompatcher + romdumpplus.dmp

**Comment by pent0** [comment]
Rom is romdumpplus.dmp what do you mean.

**Comment by xiaodong97** [comment]
I don't know how to get the ROM of my device. What I exported from rompatcher + is romdumpplus.dmp File, do not know how to export. ROM file

**Comment by pent0** [comment]
romdumpplus.dmp file is ROM file. Copy it to your PC through USB drive.
