### ISSUE TITLE
Memory leak issues

### ISSUE THREAD

**Issue by UroshUchiha** [EKA2L1/EKA2L1#20]
I came across two games that during the installation have a memory leak issue. In a couple of seconds, they take all available RAM until the PC shuts down.

First game is called FIFA 2009 for Symbian versions 9.1, 9.2 and 9.3
Here's the log file I managed to get before I had to close the emulator before my PC turned off: 
[fifa2009.log](https://github.com/bentokun/EKA2L1/files/2101705/fifa2009.log)

Second game is called Motocross Masters for Symbian versions 9.4 and 9.5. S60 (5th (Symbian^1) and 5th (Symbian^3)). Here's the log: 
[motocross_masters.log](https://github.com/bentokun/EKA2L1/files/2101711/motocross_masters.log)

**Comment by UroshUchiha** [comment]
Another game that causes memory issue is called Face Boxing for Symbian (11, 9.4). S60 (5th (Symbian^1) and 5th (Symbian^3))
Log file stops at camerawrapper.dll so not sure if that one causes issues with this one: 
[EKA2L1.log](https://github.com/bentokun/EKA2L1/files/2101733/EKA2L1.log)

**Comment by bentokun** [comment]
The installer should be fixed by now, you can try, but games are not running.

**Comment by UroshUchiha** [comment]
Memory issue is fixed from what I tested
