### ISSUE TITLE
failed to install device

### ISSUE THREAD

**Issue by bruceluo111** [EKA2L1/EKA2L1#201]
I selected the rom and rpkg file like the wizard says,then it started installing, but after a while, the logger shows:

E { eka2l1::loader::determine_rpkg_symbian_version_through_platform_file: Unable to load platform.txt in Z:\Resources\Versions. }
W { eka2l1::loader::determine_rpkg_symbian_version: First method determining Symbian version failed, second one begins }
E { eka2l1::loader::determine_rpkg_product_info_from_platform_txt: Failed to load the file. }
W { eka2l1::loader::determine_rpkg_product_info: First method of determining product info failed, start the second one. }
E { eka2l1::loader::install_rpkg: This device (RM-409) failed to be install, revert all changes }

no matter what model rom and rpkg I tried, always the same result, failed to install device.

**Comment by pent0** [comment]
Sorry for your inconveniece. Please go to File/Preferences/System and check if any device is available. Thank you.

**Comment by bruceluo111** [comment]
> Sorry for your inconveniece. Please go to File/Preferences/System and check if any device is available. Thank you.

yes, there are 2 models that I just installed , then what?
I didn't see any phone interface, just the emulator's black background, is that normal?
how do I install sisx app or games?  install package?

**Comment by pent0** [comment]
Yes, it's a bug we have known. 

> I didn't see any phone interface, just the emulator's black background, is that normal?
Yes this is normal.

>how do I install sisx app or games? install package?
Yes. Use common sense. If you don't have much English knowledge, there's a chinese translation that you can choose in File/Preferences. After installing, use "Launch apps" and launch your game. For list of game compatible, refers to this [repo](https://github.com/EKA2L1/Compatibility-List/issues)

I will keep this issue open though, until I can make that message disappear.

**Comment by pent0** [comment]
I think some people can reproduce this, but I can't personally. There are new releases which may hint more on why it's failing. If you have times you can upgrade and try those. Upgrade by replacing the entire content on the ZIP. Thanks for your cooperation.

**Comment by bruceluo111** [comment]
> I think some people can reproduce this, but I can't personally. There are new releases which may hint more on why it's failing. If you have times you can upgrade and try those. Upgrade by replacing the entire content on the ZIP. Thanks for your cooperation.

I managed to install and play the tian di dao.sisx,  but this game needs to send message to allow me to continue the game, how to proceed the game? how to make the game think I already send the message successfully? is there a way to solve this?

**Comment by pent0** [comment]
Hell Striker? Sorry I cant help much now. We need to implement proper sms service for it. For now the sms server only allow 7 Days Savalation cracked to get pass the sms screen.

**Comment by bruceluo111** [comment]
> Hell Striker? Sorry I cant help much now. We need to implement proper sms service for it. For now the sms server only allow 7 Days Savalation cracked to get pass the sms screen.

the game is Hell Striker 2,   so you mean basically, the emulator can only play games that don't need sms service?  when will you guys implement the proper sms for such games? do you have any plan?

**Comment by pent0** [comment]
Yes, thats correct. No plan. We are not paid. We do what we like.

**Comment by pent0** [comment]
> Please wait for more news. I will ping you on Github in case its available.

Maybe its your english but you seems kind of impatient. I dont understand the rush. Again I am kindly notify you when its ready.

**Comment by bruceluo111** [comment]
my English is fine, I'll just keep an eye on this emulator until it supports such games

**Comment by pent0** [comment]
I will rename this issue. The device install failure does not have much clue right now. I'm asking testers on Discord server if they ever get it.

**Comment by Ink321** [comment]
There is a version of the game Hell Striker 2 which completely works without SMS activation, although it has a number of limitations, unlike the final version with SMS activation. But I'm afraid the right to publish it remains with the much respected pent0. In addition, the demo version works great.

**Comment by pent0** [comment]
Try to find other means to communicate on Discord. Sharing installation is disallowed here due to legal respect.
