### ISSUE TITLE
Win7 can open the program, but the installed games cannot be opened

### ISSUE THREAD

**Issue by LuckyFishGeek** [EKA2L1/EKA2L1#204]
The picture below is a screenshot of the 7days game error
![Snipaste_2020-10-10_10-53-39](https://user-images.githubusercontent.com/29472751/95644401-06a3fc00-0ae9-11eb-8ce6-e1225d0401dc.png)
![Snipaste_2020-10-10_10-53-53](https://user-images.githubusercontent.com/29472751/95644402-073c9280-0ae9-11eb-9bd7-89c15d901fca.png)

Error report of Sky Force Reloaded game

![Snipaste_2020-10-10_11-10-42](https://user-images.githubusercontent.com/29472751/95644445-51257880-0ae9-11eb-871a-647cb24e29f8.png)
![Snipaste_2020-10-10_11-10-52](https://user-images.githubusercontent.com/29472751/95644446-52ef3c00-0ae9-11eb-981f-fa5c526b7495.png)

**Comment by pent0** [comment]
Please when report issue:
- Attach log
- The device you are using (5320 or n86, etc...)
- Your PC specs

Thanks a lot. You give me no information to solve things right now.
