### ISSUE TITLE
Colin McRae Rally 2005 cracked

### ISSUE THREAD

**Issue by Ink321** [EKA2L1/EKA2L1#207]
If you start and wait a VERY long time, the game starts to start. But then the emulator just stops (does not freeze), there is not enough memory - is this even possible?
![1](https://user-images.githubusercontent.com/70818773/95775288-ce5c1380-0cca-11eb-889d-14b58f16ce74.png)
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/5366698/EKA2L1.log)

**Comment by bronnel** [comment]
yes I want this game badly , mine also does not start

**Comment by Ink321** [comment]
I managed to patch it so that only one name was displayed in the menu, I really want to check ...

**Comment by Ink321** [comment]
Requiem of Hell, The Roots - Gates of Chaos, Xanadu NEXT also have problems with slow loading.

**Comment by Ink321** [comment]
Now it works.
