### ISSUE TITLE
Unimplemented object executor for function 0x28

### ISSUE THREAD

**Issue by Ink321** [EKA2L1/EKA2L1#209]
A common mistake for games that run on a real smartphone n-gage, but were not created for it. For example, the log of the game Hell Striker I demo.
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/5386372/EKA2L1.log)

**Comment by pent0** [comment]
Fixed in a42753e64ae160932ce2eacb8195ae357d933264
