### ISSUE TITLE
Parser: Ignoring IF Block cause missing files

### ISSUE THREAD

**Issue by UroshUchiha** [EKA2L1/EKA2L1#21]
Chess pro V hangs the installer. I waited a couple minutes and nothing changed. 
This game is for Symbian version 9.1, 9.2, 9.3 and 9.4

The log file is here: 
[EKA2L1.log](https://github.com/bentokun/EKA2L1/files/2101764/EKA2L1.log)

**Comment by pent0** [comment]
Fixed in 4824e08530cd88e30fe26ba74075e733875254cd
