### ISSUE TITLE
Doesn't work under OpenGL 3.2

### ISSUE THREAD

**Issue by paradagon768** [EKA2L1/EKA2L1#210]
My Pc Specs: 4gb Ram
Intel Core I3 m350 2.27 Ghz
WINDOWS 7 64 Bit

Error log:
I { eka2l1::desktop::emulator::stage_one: EKA2L1 v0.0.1 (master-03ce9668) }
E { eka2l1::desktop::emulator::stage_two: No current device is available. Stage two initialisation abort }
E { eka2l1::drivers::emu_window_glfw3::init: Can't create window! }

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/5408231/EKA2L1.log)

**Comment by pent0** [comment]
Send pc specs more. You have not sent the GPU. Use opengl version checker tool. Thanks

**Comment by pent0** [comment]
Next time not following the formula we made = immediate close

**Comment by paradagon768** [comment]
My pc supported opengl 2.1 Intel Hd Graphics Family

**Comment by pent0** [comment]
Can I ask more detail. Please Ctrl + R, type dxdiag and send me the screenshot of that window. If your PC is opengl 2.1 then it might be too old and is not near 3.2

**Comment by paradagon768** [comment]
![image](https://user-images.githubusercontent.com/73171441/96585423-438da100-12e8-11eb-8848-645bf1dbb315.png)

**Comment by Symbian9** [comment]
GPU: ATI Radeon Xpress 1250

```
$ ./eka2l1
-------------- EKA2L1: Experimental Symbian Emulator -----------------
I { stage_one: EKA2L1 v0.0.1 (master-78488e9d) }
E { stage_two: No current device is available. Stage two initialisation abort }
E { init: Can't create window! Check if your PC support at least 3.1! }
dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x00000000000000)
Segmentation fault
```

**Comment by pent0** [comment]
Sorry, I will adjust the message. About your GPU, it's very old, please check the mesa and grab your OpenGL version!

**Comment by Symbian9** [comment]
> please check the mesa and grab your OpenGL version!

What you mean? Does it provide some sort of workaround?

**Comment by pent0** [comment]
Literally check your opengl version. Your GPU is too old, I doubt it supports OpenGL 3.2 for emulator to run.

**Comment by Symbian9** [comment]
>  Your GPU is too old, I doubt it supports OpenGL 3.1

What about software GL? Would it allows run EKA2L1 on old GPU?

**Comment by pent0** [comment]
If you can find any software GL that supports OpenGL 3.1, it should work. We don't plan to support any older OpenGL version.

**Comment by artem78** [comment]
I have the same problem and similar PC configuration:
-  Intel Core i3-550 3200 Mhz with Intel HD Graphics
- 4Gb memory
- OS: Windows 7 64bit (6.1.7601.23539)

My current OpenGL version is also 2.1 and the latest version of video driver already installed.

Did anybody find any solution? Is it possible to run EKA2L1 with emulated videocard (maybe in virtual machine)?

**Comment by pent0** [comment]
Please find a driver for VM that support at least OpenGL version 3.1. I can not lower down the bar unfortunately. Maybe you can try host gpu driver.

**Comment by artem78** [comment]
I found and installed Mesa3D drivers from [here](https://github.com/pal1000/mesa-dist-win). Message "Can't create window!" disappeared, but "No current device is available. Stage two initialisation abort" is still there.

**Comment by pent0** [comment]
You have to install a device! Does it show the UI?

**Comment by artem78** [comment]
No. Program terminates after that.

------- Первоначальное сообщение -------

**Comment by artem78** [comment]
And there are no any additional information in log file.

------- Первоначальное сообщение -------

**Comment by artem78** [comment]
I found crash files. Does it help you to identify problem?
[eka2l1 crash files.zip](https://github.com/EKA2L1/EKA2L1/files/5646675/eka2l1.crash.files.zip)

**Comment by pent0** [comment]
It's very vague, only show it's an access violations. EKA2L1 is only supported from Windows 7 though :( Maybe that's the reason? Anyway else the emulator should runs fine with no device (you can download the executable and check out in host machine). I will try to lower down the requirements in future!

**Comment by artem78** [comment]
I run EKA2L1 emulator and have crash on Windows 7 host machine, not XP vm. I downloaded build from [here](https://github.com/EKA2L1/EKA2L1/releases/tag/continous). Are there any newer versions and maybe I can try it?

**Comment by artem78** [comment]
[Video_2020-12-05_222757.zip](https://github.com/EKA2L1/EKA2L1/files/5647748/Video_2020-12-05_222757.zip)

**Comment by artem78** [comment]
I solve OpenGL issue by run EKA2L1 on Linux virtual machine with hardware acceleration disabled.
