### ISSUE TITLE
Is it possible that the n-gage server will restart in the future

### ISSUE THREAD

**Issue by LuckyFishGeek** [EKA2L1/EKA2L1#211]
Now that six can run on the computer, is there any technical hacker to further crack n-gage and then build a server maintained by enthusiasts, so that everyone can play n-gage online again

**Comment by LuckyFishGeek** [comment]
Thank you very much to @pent0  for making this simulator, which allows us to play the games of the school days on the computer.  Wish you health and happiness🥰

**Comment by pent0** [comment]
谢谢。中国人含忠诚，因此我喊高兴！I hope you happy with emulator, for more live support join in the Discord if possible. This is effort of many people.

About this issue, it's out of our reachh.... We need to ask other people about this, sorry.

**Comment by pent0** [comment]
But more information: If we have infos about how the server receive/send packets, we might got a clue. But we need to ask our Chinese/Russian friends if they have collected anything on that!

**Comment by LuckyFishGeek** [comment]
I have collected almost all applications and games about s60 v 3 and symbian 3 on the Chinese Internet, and I am happy to provide all the resources if necessary.  Thank you again for your enthusiasm

**Comment by pent0** [comment]
Yes, if you have resources about N-Gage (phone) and N-Gage (service on s60v3), please share it on the Discord link in the README. Thanks a lot

**Comment by LuckyFishGeek** [comment]
Okay, I look for relevant resources on the Chinese Internet

**Comment by LuckyFishGeek** [comment]
By the way, I like to eat Vietnamese fried pho hahaha
