### ISSUE TITLE
Compatibility error

### ISSUE THREAD

**Issue by edumen2** [EKA2L1/EKA2L1#215]
Hello, I have a problem, the application is not compatible with my Android 4.2.2 and I wanted to know if you can send me the apk with my version of android 4.2.2 please wait a long time for this emulator, here is my email so that send me the apk edumen2ahd2@gmail.com

![Screenshot_2020-10-29-01-59-26](https://user-images.githubusercontent.com/73629289/97528297-2150ee80-198c-11eb-80eb-b823a3699a83.png)
![Screenshot_2020-10-29-01-59-32](https://user-images.githubusercontent.com/73629289/97528314-2ada5680-198c-11eb-884f-dfb0edf01468.png)

**Comment by nikita36078** [comment]
The emulator requires Android 5.0 64-bit, it's impossible to adapt it for older versions or 32-bit.

**Comment by gogoichandan21** [comment]
Working on my lenovo L38111 running on pixel experience+ custom rom,
android 10.0. Is there any s60v3 rom dump available?

**Comment by gogoichandan21** [comment]
I would be pleased if infinite dreams superminers game work.❤️❤️
