### ISSUE TITLE
Newer windows builds no longer launching

### ISSUE THREAD

**Issue by bronnel** [EKA2L1/EKA2L1#223]
the newer builds for windows can no longer launch properly after installing a device 
also clicking on system preferences force closes the program, 
https://imgur.com/vz0FhKt

**Comment by pent0** [comment]
I can't reproduce this. Please clean the content of the patch folder and copy the content of newer build patch's folder, not override it. Hope it helps

**Comment by pent0** [comment]
Make sure your patch folder does not have files like mediaclientaudio.map, instead it's mediaclientaudio.dll.map. If it still happening, please pack your whole EKA2L1 and upload it for testing. Sorry for inconvenience.

**Comment by bronnel** [comment]
@pent0 thanks for your response ,
I did a clean install , the exact steps is as follows
downloaded from github 
unpacked
launched for first time without problem'
asks to install device
I install 5320
then close then relaunch
this is what I get in the picture
https://imgur.com/vz0FhKt

https://mega.nz/file/hg8S2axD#banDLu6aQ4M0mpBtae2zKWxb92q2M9Jr204-1i9ISQs

**Comment by pent0** [comment]
I'm sorry, I can't reproduce it. The bundle you gave launch fine for me.

Can you please try to find the change that make it unable to launch the emulator for you? Please traverse through this [tree]( https://github.com/EKA2L1/EKA2L1/commits/master) for me and download each build and try it out. Sorry for this. I can decide what to do when I know what changes broke it for you.

**Comment by bronnel** [comment]
This issue is now fixed with [**this commit**](https://github.com/EKA2L1/EKA2L1/commit/930e44ee6530f09a455ebdd11f2525d231ec850c) thank you.
