### ISSUE TITLE
help me to install on ubuntu

### ISSUE THREAD

**Issue by mugi789** [EKA2L1/EKA2L1#228]
![gambar](https://user-images.githubusercontent.com/32443765/99939626-1592f500-2d9d-11eb-8345-774b4a8e7ba0.png)

**Your PC or smartphone specs**
- Ubuntu 18.04.5 LTS x86_64
- Pentium T4400 (2) @ 2.200GHz
- NVIDIA GeForce 310M

**Comment by pent0** [comment]
Not a support forum

**Comment by pent0** [comment]
Please go to Discord or watch Youtube for instructions.
