### ISSUE TITLE
Support for 32-bit ARM

### ISSUE THREAD

**Issue by spmd109** [EKA2L1/EKA2L1#235]
Please make it compatible with 32 bit SoC dev, there are still many 32 bit android devices users that need this cool apps, i'm sure newer android devices users dont give a fvck of this apps, they are busy upgrade and upgrade to a new fckin more powerfull devices

**Comment by pent0** [comment]
Don't disregard other people in order to gain your advantage. If theres no need to use this app a 64bit version for android would not have been born. Take that rude adittue off here, you are also disregarding our works.

**Comment by pent0** [comment]
Regardless, the 32bit support is being added in ccdd branch, so its being worked on. Wait for further announcements

**Comment by EduMen2A** [comment]
Is there a possibility that the emulator is compatible with Android 4.0 onwards?

**Comment by pent0** [comment]
No, please consider upgrade your phone. Android 4.0 is too old, our code uses API that are not comfortable with them no more. If you are using embedded device that are cheap and run kitkat then I suggest you change it to better device.

**Comment by EduMen2A** [comment]
My Android is 4.2.2 and 32 bit
![Screenshot_2020-12-26-02-15-10](https://user-images.githubusercontent.com/62011532/103145962-eb787e00-4720-11eb-994b-8fb078b2676e.png)

**Comment by pent0** [comment]
> No, please consider upgrade your phone. Android 4.0 is too old, our code uses API that are not comfortable with them no more.

i said it, deal with it

**Comment by Reiju** [comment]
There is no point to write Emulator for older devices. 
1st almost nobody is (who is aware of problems and back doors) using those devices. 
2nd those devices are sooo slow it would run Emu in 5fps....

**Comment by User-32** [comment]
Some android phones still use 32-bit.

**Comment by pent0** [comment]
Why are you stating facts again no one asked

**Comment by EduMen2A** [comment]
and why not do a test to see if the emulator runs on Android 4.0 and see how many fps each game goes.

**Comment by pent0** [comment]
> No, please consider upgrade your phone. Android 4.0 is too old, our code uses API that are not comfortable with them no more.

I already said it. it depends on whether you can read or not. I will try to support android 32-bit. But your device is already too old.

**Comment by iMattzin** [comment]
my phone is Moto G5 S, Android 8, 32 bits and unfortunately this emulator does not work. But thanks for confirming a possible 32-bit version

**Comment by iMattzin** [comment]
my phone is the Moto G5 S, Android 8, 32 bits and unfortunately this emulator does not work. But thanks for confirming a possible 32-bit version

**Comment by Reiju** [comment]
Are you sure about this? MOTO G5 S using snapdragon 430 which is 64bit....
![Screenshot_20210104-080703](https://user-images.githubusercontent.com/6968996/103509662-ed021e80-4e63-11eb-9358-586e4707b959.png)

**Comment by pent0** [comment]
Some phones have low RAM so manufacturers installed 32bit android on them to prevent disasters....

**Comment by iMattzin** [comment]
I don't understand but the apk doesn't install on Moto G5S, is there any way to activate this 64 bit?

**Comment by iMattzin** [comment]
remembering that Moto G5S runs emulators like PPSSPP, Drastic, Nintendo 64 and others, does this Nokia emulator consume more RAM than these other emulators?

**Comment by pent0** [comment]
No 32-bit recompiler, we use Citra's CPU emulator. I'm working on it, no
need for the demand reminds. It's Symbian OS emulator.

Vào Th 2, 4 thg 1, 2021 vào lúc 14:26 iMattzin <notifications@github.com>
đã viết:

**Comment by pent0** [comment]
>  I don't understand but the apk doesn't install on Moto G5S, is there any
way to activate this 64 bit?

Buy a new phone?

Vào Th 2, 4 thg 1, 2021 vào lúc 14:23 iMattzin <notifications@github.com>
đã viết:

**Comment by pent0** [comment]
32-bit support is experimentally added. Check [here](https://12z1.com/jekyll/update/2021/01/25/32-bit-android-support.html)

**Comment by spmd109** [comment]
Thank you very much for your great works dev, forgive me for my past words.
it has worked on my xperia z using the official lollipop rom. 
actually, I prefer my Xperia Z use the Custom Jelly Bean ROM because it can be overclocked.
Can you please make it compatible with Android 4.3.1 Jelly Bean?

**Comment by pent0** [comment]
Fixed
