### ISSUE TITLE
EKA2L1 does not install on Android 8.x

### ISSUE THREAD

**Issue by rizalmart** [EKA2L1/EKA2L1#237]
I tried to install EKA21 apk on Android 8 but the unable to install package it always fail

**Comment by 1322571215** [comment]
有病吧 老是发给我 去死，混蛋!



---Original---

**Comment by pent0** [comment]
取消Watch上github如果你不想看。谢谢

**Comment by pent0** [comment]
> I tried to install EKA21 apk on Android 8 but the unable to install package it always fail

Your android must be 64bit. Please check online tools to see, this issue is closed
