### ISSUE TITLE
The last layer of protection for N-gage games - cwdynlog.dll

### ISSUE THREAD

**Issue by Ink321** [EKA2L1/EKA2L1#238]
It's about games:
Bugbear.Glimmerati.v1.0.51
Digital.Legends.One.v0.45
Gameloft.Asphalt.Urban.GT.2.v2.0.194
Gryphondale.Studios.Civilization.v1.1.4
Razorback.Warhammer.40.000.v0.6.9

When the game starts, this temporary cwdynlog.dll library is created, along the path c:\system\cwdynlog.dll. It runs probably separate parts of the game code in ****.dat files and checks the possibility of overwriting the game files (which is not possible on a real licensed memory card) + the ability to rename/format the memory card. Any change in the functions associated with the work of this library leads to the inability to load the game code.
Is it possible to take control of this library?

**Comment by pent0** [comment]
I already know it, why not implement what they need instead? I throw them on my local machine and has deleted them though :(. I will not try to take control of this library:
- The MMCID of the card must be given by the user to preserve legality of what the game needs.
- The files protection can probably be easily bypassed.
If you try to take control of this library you have to give what each function of the library does. You can write symbian patch DLL for emulator to replace them at runtime.

**Comment by Ink321** [comment]
О   О
    О

**Comment by Ink321** [comment]
Okay. But then the question arises. Will the emulator add the function of loading information about the memory card and its connection with the game? And how can information be added?

**Comment by pent0** [comment]
Talked on Discord. You have to provide memory card ID. That's why I made that tool. When the driver responsible for it is requested a pop up will show up. This pop up will not show up if the ID is provided also in game dump (probably through some files like ngagestarter.txt)

**Comment by yfaizin1** [comment]
how to play ngage v2.0 for  ektensi  file *.ngage

**Comment by Apihplays** [comment]
> how to play ngage v2.0 for ektensi file *.ngage

not supported yet

**Comment by pent0** [comment]
As discussed with Razvan, there will be a YML that stores MMC ID based on executable MD5 hash, will implement this and the UI needed it. This is the response to the upper comment.
