### ISSUE TITLE
Some games [Android] black screen show

### ISSUE THREAD

**Issue by daichiyamada72** [EKA2L1/EKA2L1#239]
![Screenshot_2021-01-10-11-49-20-29_931c35d66d4d9ced7618500443142954](https://user-images.githubusercontent.com/77099813/104115888-2c37e000-533a-11eb-9d4c-99718af5bfe1.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**smartphone specs**

Name : Realme 7. 
Processor :  helio g95
GPU : Mali g76 MC14

**Your emulator configuration**
- The phone model ( 5230,5800,n95 & N-Gage QD)
Using.
**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file
- 
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/5792326/EKA2L1.log)

**Comment by pent0** [comment]
Invalid issue, fill all
