### ISSUE TITLE
Black screen on kirin 970 android 10

### ISSUE THREAD

**Issue by jurises99** [EKA2L1/EKA2L1#247]
Device huawei P20
CPU: Kirin 970
GPU: Mali-G72
O.S.:Android 10 
Emui 10
I already installed the RKPG and rom successfully 
I tried to run crash bandicoot, crusade of destiny and other games, they all have black screen not even a sound
Down below is the attached screenshot and log.

[android.log](https://github.com/EKA2L1/EKA2L1/files/5888210/android.log)

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/5888169/EKA2L1.log)

![Screenshot_20210128_230430_com github eka2l1](https://user-images.githubusercontent.com/22735064/106157362-9915fb80-61bd-11eb-8612-2f7303e8929d.jpg)

**Comment by pent0** [comment]
Try game that supposed to work on pc version and repory back the log with an android.log and eka2l1.log.

**Comment by pent0** [comment]
Also 5530 is not yet to be tested and supported. We dont have rom data of it to test yet. Please try other devices for now.

Also crusade is an symbian^3 game, and crash is an s60v3 games. Dont expect them to run on s60v5...

**Comment by pent0** [comment]
Is there any feedback? I will close this

**Comment by pent0** [comment]
Close as inactive.
