### ISSUE TITLE
Set default refresh rate value to 60hz

### ISSUE THREAD

**Issue by stevenfelix505** [EKA2L1/EKA2L1#249]
Yes, you read the title right, can you do that?

Every time I update the EKA2L1 app, the refresh rate setting is reset from 60hz to 30hz.

**Comment by pent0** [comment]
60fps may create gameplay unwanted issue, but about the refresh rate restart, thats the backend issue. Will note

> Yes, you read the title right
No

**Comment by stevenfelix505** [comment]
Thank you for resolving this problem, I can close the issue from now.
