### ISSUE TITLE
It doesn't work, I don't understand, help me please

### ISSUE THREAD

**Issue by IJustWantToPlayAGameForCornSake** [EKA2L1/EKA2L1#251]
**Describe the bug**
I extracted it and ran the .exe and it came up with the error that it couldn't find vcruntime140_1.dll.  I searched my computer for it and found something called vcruntime140.dll and thought "close enough" and renamed it and put it in the same folder as the .exe.  After that, I ran it and it says "The procedure entry point_CxxFrameHandler4 could not be located in the dynamic link library C:\Users\Allen\Desktop\Emulator\eka2l1.exe."  All I want to do is use this emulator to player The Elder Scrolls Travels: Shadowkey.  I am not a programmer (obviously) and I don't know how to fix this stuff when it doesn't work right out of the box.  I just want to click the .exe and have it do what it is supposed to, not have to reprogram the whole darn thing myself.  Please, I beg of you, can some good Samaritan just compile a working version of this and post it here?  I am so done with GitHub expecting me to know how to program this stuff for it.  Please help.

**To Reproduce**
See above.

**Expected behavior**
The program would start running.

**Your PC or smartphone specs**
Windows 8 with Nvidia something-or-other.  I don't know that that matters, though.

**Comment by pent0** [comment]
No one asked you to know. You could have write 2 lines. Please don't replace DLL like that, download and install this exe [here](https://12z1.com/download/#note-for-windows) to fix vcruntime_140.dll missing problem

**Comment by pent0** [comment]
This error can also be [googled](https://www.drivereasy.com/knowledge/how-to-fix-msvcp140-dll-is-missing/) for fix

**Comment by IJustWantToPlayAGameForCornSake** [comment]
My apologies for my frustration, it's jus that I am accustomed to having programs which work perfectly for any old idiot, like myself.  If I can't rant, how do I express the depths of my frustration to the powers that be?  Anyway, as for your assistance, it worked, thank you.  I will go back to banging two rocks together and giggling in my cave now.
