### ISSUE TITLE
macOS: "No current device is available. Stage two initialisation abort" when running executable

### ISSUE THREAD

**Issue by fomalsd** [EKA2L1/EKA2L1#268]
Hi, getting this error when trying to run the newest CI build on macOS 10.14.6 (Intel mac):
```
-------------- EKA2L1: Experimental Symbian Emulator -----------------
I /Users/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:69 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-58f5af15)
E /Users/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:125 [Frontend.Cmdline]: No current device is available. Stage two initialisation abort
dynarmic: macOS MachHandler: Exception was not in registered code blocks (rip 0x00000000000000)
Segmentation fault: 11
```
No GUI appears and the whole thing just crashes.

**Comment by pent0** [comment]
Hi, it has been like this for a while. I have no Mac to debug so I'm not sure what happen. I will keep this issue open in help of a person who could have me debug with XCode. Very sorry!

**Comment by trzhong** [comment]
Hi, getting the same error on Linux Mint 20.1:

~/make/EKA2L1$ ./eka2l1 --listdevices
-------------- EKA2L1: Experimental Symbian Emulator -----------------
I /home/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:69 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-0e4850ab)
E /home/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:125 [Frontend.Cmdline]: No current device is available. Stage two initialisation abort

**Comment by pent0** [comment]
Hi, there is no device installed. So this is thrown. You can open up the UI and follow the brief tutorial to install a device.

**Comment by trzhong** [comment]
Hi, getting the same error on Linux Mint 20.1, No GUI appears and the whole thing just crashes.

~/make/EKA2L1$ ./eka2l1 --listdevices
-------------- EKA2L1: Experimental Symbian Emulator -----------------
I /home/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:69 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-0e4850ab)
E /home/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:125 [Frontend.Cmdline]: No current device is available. Stage two initialisation abort

**Comment by pent0** [comment]
--listdevices should not be used. It just lists the devices. Just ./eka2l1?

**Comment by denizkoekden** [comment]
Running just ./eka2l1 crashes on macOS X 11.2.3 

This is the Console Output:
./eka2l1
-------------- EKA2L1: Experimental Symbian Emulator -----------------
I /Users/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:69 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-a647d0df)
E /Users/runner/work/EKA2L1/EKA2L1/src/emu/console/src/state.cpp:125 [Frontend.Cmdline]: No current device is available. Stage two initialisation abort
dynarmic: macOS MachHandler: Exception was not in registered code blocks (rip 0x00000000000000)
zsh: segmentation fault  ./eka2l1

**Comment by pent0** [comment]
Refer to my comment upper for more information. reposting won't help much.

**Comment by denizkoekden** [comment]
@pent0 yeah but you suggested to try running it without "--listdevices" and I tried only ./eka2l1 and the Error showed up.

**Comment by pent0** [comment]
I mean the problem is the same...
