### ISSUE TITLE
Symbian: List of Devices (Both Dumped and Undumped)

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#270]
The document below lists all the Devices available and unavailable to download. if you have a device that has not been dumped and want to help,  dump it and post a link to it on the official discord. for everyone else, please don't bag or harass anyone for Roms they can't provide or are just not willing dump, let's keep things civil. all the available Roms can be found by going to the Internet Archive Website and type the following into the search bar: "Symbian OS ROMs

[Google Doc](https://docs.google.com/spreadsheets/d/1jC5E28HHTjRFXohZ955Teu7u8tu3hj9DmqGaX8bBdMw/edit?usp=sharing)

**Comment by Lucas-mother3** [comment]
Great to know

**Comment by WaseemAlkurdi** [comment]
@TRR95 It seems that the `Symbian-OS-Roms.zip` archive has recently been taken down by the Internet Archive ... any chance of the file being made available somewhere else?
