### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Kareem200422** [EKA2L1/EKA2L1#273]
I thin it would be better if you did at least one of the following:
1-Make some N-Gage system apps able to run (like game manger so I can manage my games' data)
2-Make the app support Some connectivities like bluetooth and WLAN
3-Add screenshot button just like most emulators have

**Comment by pent0** [comment]
Open separate issue. Thanks for the suggestion. 1 is related to compabilty. So no need to open issue.
