### ISSUE TITLE
Cannot install nokia n-gage games 

### ISSUE THREAD

**Issue by Shoegzer** [EKA2L1/EKA2L1#274]
Attempting to install games does not work at all.  

Directory-based games: copy contents of game's system folder to "data/drives/e", then go into eka2l1 and click "file > launch apps".  Game is not recognized in app list.  Tried multiple games including some such as Elder Scrolls that others have installed, but it's not seen.

.blz-based games: copy game .blz file to data/drives/e, then go into eka2l1 and click "file > packages > install" and run the blzinstapp util.  eka2l1 immediately crashes.

Since this system is linux/ext4, wondering if there are issues with case sensitivity (noticed directory is called "data/drives/e/system" and not "data/drives/e/System".
 
Test system is linux mint 20.1 with kernel 5.11 compiled with gcc-10.2.0.  Testing against commit bb9be0952aeafd29dac452f89467132b5a6a269a.

**Comment by pent0** [comment]
Please go to the discord server for support, you need an existing N-gage device to be installed on the emulator, or else it won't show anything.

We never specified it's a N-Gage emulator, and of course BLZ is not SIS format, you need to use the BLZ installer app running emulated inside the emulator to install it

**Comment by Shoegzer** [comment]
@pent0 This isn't a matter of support, there is a bug and possibly a regression.  I've done all of the things you've mentioned - I've installed an n-gage device, and i did use the blz installer - but when I try to launch the installer with the .blz file is in data/drives/e, eka2l1 crashes.  If i remove it, i can launch the installer but then of course there's nothing to install.

I realize eka2l1 is much more than just an n-gage emulator as it emulates the more generalized Symbian.  The above was a basic initial test chosen due to the fact that it's been widely oberverved to have worked in the past and should have worked here.

Please reopen this issue and let me help you work on it?

**Comment by pent0** [comment]
You can try File/Preferences and validate drie again. It works fine on case insensitive android so I have doubts. I will try myself in vm tomorrow

**Comment by Shoegzer** [comment]
Thank you @pent0.  Case sensitivity was the issue, and validate devices resolved it, so no need for logs of gdb backtracing.  

I'll (re)close this issue now.
