### ISSUE TITLE
Quality of Life Changes: Add Config Tab to Preferences

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#276]
Instead of having to edit config.yml to everytime someone wants to turn ecom or socket off or on, a new tab in the Preferences menu with the settings not in the other tabs should be added. hovering over one of these settings should open a pop-up that gives more info what it dose and when it should be used. 

For testing purposes, any number of the services or features could cause issues with some apps and playing with these settings could get games and software to run, simplifying access to them would be a good QOL improvement.

**Comment by pent0** [comment]
This is done
