### ISSUE TITLE
I hope that the game can be set separately, adding the right joystick mapping of the handle

### ISSUE THREAD

**Issue by huchao2007** [EKA2L1/EKA2L1#277]
I hope that each game can be set individually, just like j2me loader.
In addition, the button mapping can increase the handle right joystick mapping like ppsspp, so that when playing some shooting games, the angle of view can be changed at the same time, which is much more convenient. Also because the handle buttons are not enough, it is not easy to set up.

**Comment by bronnel** [comment]
please add right analog stick support for gamepads such as DS4 , xbox
