### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Master811129** [EKA2L1/EKA2L1#279]
Hello, unfortunately, I can't find any icon file in the source code but there is an icon for the android version so could you please put the icon file in the source code, or if it does exist specify its path for me? Thanks!

**Comment by pent0** [comment]
You can traverse through mipmap folder for [icon](https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/android/app/src/main/res/mipmap-xxxhdpi/ic_ducky.png)

Here is link to transparent HD [version](https://imgur.com/a/yNKvjGq)

Close the issue if it's satisified.

**Comment by Master811129** [comment]
Thank you. do you use this icon on other platforms?

**Comment by pent0** [comment]
Yes, its used on PC version too.
