### ISSUE TITLE
Built-in Updater

### ISSUE THREAD

**Issue by soaresden** [EKA2L1/EKA2L1#283]
Hi ! 

I'm so excited about all energy developed here for this fantastic device so misunderstood !
Because of that much energy, I would suggest : 

- Checking version number at startup and show a dialog to update with list of changes
(like Duckstation does)
![image](https://user-images.githubusercontent.com/54243866/119038486-751c3700-b9b3-11eb-87bc-8ddfcffe82ef.png)

- An Update entry on menu bar showing similar things : 
![image](https://user-images.githubusercontent.com/54243866/119038388-5ae25900-b9b3-11eb-8bc9-576c9fac4aab.png)

Stay Awesome ♥

source : https://github.com/stenzek/duckstation/blob/master/src/duckstation-qt/mainwindow.ui
and 
https://github.com/stenzek/duckstation/blob/master/src/duckstation-qt/mainwindow.cpp

**Comment by yfaizin1** [comment]
can you help me how to install method firmware by  vpl (what is ektensions
file to support the intallationbmethod firmware) and how to creat file
*.RPKG?

Pada tanggal Jum, 21 Mei 2021 2.37 AM, soaresden ***@***.***>
menulis:

**Comment by pent0** [comment]
Added in #c456744bc8007b125d57bcac6f206e8c3e9e891d
