### ISSUE TITLE
Can't install SIS file on External Storage

### ISSUE THREAD

**Issue by stevenfelix505** [EKA2L1/EKA2L1#284]
**Describe the bug**
So, the storage on my smartphone is getting full, I recently found this post : https://m.facebook.com/groups/812987536190487/permalink/957148995107673/
I mimicked the way he moved the data folder in EKA2L1 to the memory card, and now I can't install any sis/sisx file. Is this related to SAF (Storage Access Framework)?

**To Reproduce**
1. Go to 'EKA2L1 Main app'
2. Click on 'Green Plus Button'
3. Click on any sis/sisx file
4. You got 'EKA2L1 has stopped' screen

**Expected behavior**
The sis/sisx file should be installed successfully on my smartphone. If sis file is detected as different version (s60v5 software on s60v1 device), it should also installed successfully.

**Screenshots**
Step 1 :
![Screenshot_20210521-151833_EKA2L1.jpg](https://user-images.githubusercontent.com/57618009/119106087-2a003380-ba48-11eb-857a-2490d57521d9.jpg)
Step 2 and 3 :
![Screenshot_20210521-151906_EKA2L1.jpg](https://user-images.githubusercontent.com/57618009/119106122-35ebf580-ba48-11eb-9a2d-a789b163b2aa.jpg)
Step 4 :
![Screenshot_20210521-151933_One UI Home.jpg](https://user-images.githubusercontent.com/57618009/119106153-3dab9a00-ba48-11eb-97ca-62c8bddf6e23.jpg)

**Your PC or smartphone specs**
- OS version : Android 10
- The CPU you are using : Exynos 7884 Octa-core (2 × Cortex-A73; 6 × Cortex-A53)
- The GPU you are using : Mali-G71

**Your emulator configuration**
- Phone model : 
1. Nokia N-Gage QD Dev (RH-29)
2. Nokia N70 (RM-84)
3. Nokia 5800 XpressMusic (RM-356)
4. Nokia 5320d (RM-409)
5. Nokia 5530 (RM-504)

**Log**
- Here it is
I ../../../../src/main/cpp/src/state.cpp:60 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-0143aa1e) T ../../../../../../kernel/src/kernel.cpp:1139 [Kernel]: Rom mapped to address: 0xb142b000 I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: ROM, base (in parent): 0x50000000, max size: 0x1230000 type: normal, access: global I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: DispatcherTrampolines, base (in parent): 0x51300000, max size: 0x4000 type: normal, access: global I ../../../../src/main/cpp/src/state.cpp:112 [Frontend.Cmdline]: Device being used: Nokia N-Gage QD Dev (rh-29) T ../../../../../../kernel/src/libmanager.cpp:371 [Kernel]: Using dll scdv_v81a.dll as patch dll for map file scdv.dll T ../../../../../../kernel/src/libmanager.cpp:414 [Kernel]: Patch scdv.dll.map has no hard requirements T ../../../../../../kernel/src/libmanager.cpp:423 [Kernel]: Shared section not found for patch DLL scdv.dll.map T ../../../../../../kernel/src/libmanager.cpp:371 [Kernel]: Using dll mediaclientaudio_v81a.dll as patch dll for map file mediaclientaudio.dll T ../../../../../../kernel/src/libmanager.cpp:414 [Kernel]: Patch mediaclientaudio.dll.map has no hard requirements T ../../../../../../kernel/src/libmanager.cpp:423 [Kernel]: Shared section not found for patch DLL mediaclientaudio.dll.map T ../../../../../../kernel/src/libmanager.cpp:371 [Kernel]: Using dll mediaclientaudiostream_v81a.dll as patch dll for map file mediaclientaudiostream.dll T ../../../../../../kernel/src/libmanager.cpp:414 [Kernel]: Patch mediaclientaudiostream.dll.map has no hard requirements T ../../../../../../kernel/src/libmanager.cpp:423 [Kernel]: Shared section not found for patch DLL mediaclientaudiostream.dll.map T ../../../../../../kernel/src/libmanager.cpp:371 [Kernel]: Using dll vibractrl_v81a.dll as patch dll for map file vibractrl.dll T ../../../../../../kernel/src/libmanager.cpp:423 [Kernel]: Shared section not found for patch DLL vibractrl.dll.map I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: anonymous2374450955, base (in parent): 0x51400000, max size: 0x54a0 type: normal, access: global, anonymous I ../../../../../../kernel/src/codeseg.cpp:202 [Kernel]: scdv_v81a.dll runtime code: 0x51400000 I ../../../../../../kernel/src/codeseg.cpp:203 [Kernel]: scdv_v81a.dll runtime data: 0x0 I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: anonymous2602865858, base (in parent): 0x51500000, max size: 0x4760 type: normal, access: global, anonymous I ../../../../../../kernel/src/codeseg.cpp:202 [Kernel]: mediaclientaudio_v81a.dll runtime code: 0x51500000 I ../../../../../../kernel/src/codeseg.cpp:203 [Kernel]: mediaclientaudio_v81a.dll runtime data: 0x0 I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: anonymous2638880794, base (in parent): 0x51600000, max size: 0x1aa8 type: normal, access: global, anonymous I ../../../../../../kernel/src/codeseg.cpp:202 [Kernel]: mediaclientaudiostream_v81a.dll runtime code: 0x51600000 I ../../../../../../kernel/src/codeseg.cpp:203 [Kernel]: mediaclientaudiostream_v81a.dll runtime data: 0x0 I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: anonymous521955031, base (in parent): 0x51700000, max size: 0xc78 type: normal, access: global, anonymous I ../../../../../../kernel/src/codeseg.cpp:202 [Kernel]: vibractrl_v81a.dll runtime code: 0x51700000 I ../../../../../../kernel/src/codeseg.cpp:203 [Kernel]: vibractrl_v81a.dll runtime data: 0x0 I ../../../../../../services/src/applist/applist.cpp:426 [Service.Applist]: Loading app registries I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: FbsSharedChunk, base (in parent): 0x10000000, max size: 0x600000 type: normal, access: global I ../../../../../../kernel/src/chunk.cpp:135 [Kernel]: Chunk created: FbsLargeChunk, base (in parent): 0x10600000, max size: 0x2000000 type: normal, access: global T ../../../../../../services/src/fbs/impls/font.cpp:960 [Service.Fbs]: Found font folder: Z:\System\Fonts\ I ../../../../../../services/src/applist/applist.cpp:129 [Service.Applist]: Failed to read caption file for menu I ../../../../../../services/src/applist/applist.cpp:445 [Service.Applist]: Done loading!

**Comment by pent0** [comment]
You can save android.log with the .../Save log and post here. This is unreadable and distracting

**Comment by stevenfelix505** [comment]
EKA2L1.log file sent to your Discord

**Comment by pent0** [comment]
[android (7).log](https://github.com/EKA2L1/EKA2L1/files/6521222/android.7.log)

This is log sent to my private
