### ISSUE TITLE
Do not understand how to use Windows

### ISSUE THREAD

**Issue by YOSI-COHEN** [EKA2L1/EKA2L1#285]
תודה רבה
הסבר לי כיצד להשתמש

**Comment by pent0** [comment]
Please use Google Translate to type in English. You first need to install a device dump into the emulator. Then you can install games. You can visit Youtube if any difficulties. We don't accept non English issue

**Comment by YOSI-COHEN** [comment]
Thank you very much for the software
I do not know how to use it, he wants me to put in rum I do not know exactly what it is
I would love an explanation
Thank you!

**Comment by pent0** [comment]
Emulator needs real files from the phone you want ro emulate. If you want to emulate:
-s60v1, ngage: You can find an Ngage ROM dump then install
-s60v3 and s60v5: You need to find a phone firmware to install to have files

After that  you can install games and play normally.

**Comment by YOSI-COHEN** [comment]
Ahh
I understood, thank you.
So if I want to run applications on Nokia C5 then I should take its firmware, and put in the system?

**Comment by pent0** [comment]
Yes, you can download firmware, then follow the UI display to get to the install firmware tutorial, then you can install SIS

**Comment by YOSI-COHEN** [comment]
TANKES

**Comment by YOSI-COHEN** [comment]
תודה

**Comment by YOSI-COHEN** [comment]
Thank you
But I can not find firmware

**Comment by YOSI-COHEN** [comment]
Thank you very much for the explanation
I have already installed the firmware
How do I currently run SIS applications
Thanks
![image](https://user-images.githubusercontent.com/82176699/119400623-1ae8e200-bce3-11eb-9c5d-beb5d4cb6711.png)

**Comment by YOSI-COHEN** [comment]
Thank you very much, I was able to run
Although it is not well processed and collapses
But I was able to run
Thanks
