### ISSUE TITLE
N-gage 2.0 support on 32 bit device

### ISSUE THREAD

**Issue by quocbao2002** [EKA2L1/EKA2L1#295]
N-gage 2.0 game work on 64 bit device but not on 32 bit because of "unable to allocate bss data from process" problem. I hope n-gage 2.0 game can run on 32 bit device in the furture like 64 bit device.

**Comment by yfaizin1** [comment]
spesifik phone bb aurora 4/32 , this phone 64 bit. play game erorr image
canot play

Pada tanggal Sen, 7 Jun 2021 1.10 AM, quocbao2002 ***@***.***>
menulis:

**Comment by pent0** [comment]
Recheck, should be fine. Not on Play Store yet

**Comment by pent0** [comment]
This all should work fine now, besides some CPU recompiler issues, which are to be opened separately.
