### ISSUE TITLE
Improvement : --device "NEM-4"  CLI for exemple

### ISSUE THREAD

**Issue by soaresden** [EKA2L1/EKA2L1#298]
**Describe the bug**

It's not a bug, just a quick suggestion to improve User Experience.
Since Ngage 2 has made great progress recently, it would be great to be able to add a --device "NEM-4" or "RM-409" (will use Ngage NEM-4) for exemple 
It could be used with every \folder in \roms
![image](https://user-images.githubusercontent.com/54243866/121782282-1a888c00-cba9-11eb-9052-eb10e3e37974.png)

![image](https://user-images.githubusercontent.com/54243866/121782061-14de7680-cba8-11eb-947a-3d9658e12b3d.png)

In this way we can directly launch roms like : 

Tomb Raider Ngage 1:
eka2l1 --device "NEM-4" --mount "TOMBRAIDER" --run "x0101fbf9d" 1

Any Ngage 2 game : 
eka2l1 --device "RM-409" --run "0x20007b39"

**To Reproduce**

**Expected behavior**
Adding this --device cmd that will give user control over the device used

**Screenshots**

**Your PC or smartphone specs**
- OS version : W10
- The CPU you are using 
- 
![image](https://user-images.githubusercontent.com/54243866/121782231-d1383c80-cba8-11eb-9cd7-b92793abf6f6.png)

- The GPU you are using
![image](https://user-images.githubusercontent.com/54243866/121782240-df865880-cba8-11eb-943e-77a28f959787.png)

**Your emulator configuration**
- The phone model you are using (RM-409, 5320 Express Music for example)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file

**Comment by pent0** [comment]
Fixed in #311
