### ISSUE TITLE
game n-gage 2.0 trial_version

### ISSUE THREAD

**Issue by yfaizin1** [EKA2L1/EKA2L1#300]
how to play game n-gage 2.0 trialversion, play on Louncher n-gage v1.40 to fullversion game. How to craked the game trial version game n-gage 2.0 (*.ngage). Thanks ☺️
[]()https://youtu.be/uiiQ826qHBE

**Comment by quocbao2002** [comment]
> how to play game n-gage 2.0 trialversion, play on Louncher n-gage v1.40 to fullversion game. How to craked the game trial version game n-gage 2.0 (*.ngage). Thanks ☺️
> https://youtu.be/uiiQ826qHBE

unless another crack team like binpda is working, n gage 2.0 trial games will never been crack

**Comment by pent0** [comment]
We do not support cracking trail games. This is not our responsbility.
