### ISSUE TITLE
HellStrikerII Can't display and run after installation

### ISSUE THREAD

**Issue by LuckyFishGeek** [EKA2L1/EKA2L1#319]
**Describe the bug**
HellStrikerII Can't display and run after installation

Terminal error reporting
![Snipaste_2021-08-02_15-51-10](https://user-images.githubusercontent.com/29472751/127824019-17b31478-05f7-46db-a121-aa5be42dbfa8.png)

**To Reproduce**
![Snipaste_2021-08-02_15-47-58](https://user-images.githubusercontent.com/29472751/127824068-ffd1ee9d-6f48-45f9-8191-b1fbea782d7b.png)
![Snipaste_2021-08-02_15-48-11](https://user-images.githubusercontent.com/29472751/127824074-ad7d1ff5-603b-41ee-afb1-abfc6973600d.png)
![Snipaste_2021-08-02_15-48-42](https://user-images.githubusercontent.com/29472751/127824080-404a241f-ad2f-416a-afb6-cf9b99a8b958.png)

**Your PC or smartphone specs**
- OS version  WIN7 64
- I7 4650U
- nuclear display

**Your emulator configuration**
- RM-409, 5320 

**Log**
I D:\a\EKA2L1\EKA2L1\src\emu\qt\src\state.cpp:64 [Frontend.Cmdline]: EKA2L1 v0.0.1 (master-4ed04dbc)
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:27 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:28 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:27 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:28 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:27 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:28 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:27 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\config\include\config/app_settings.inl:28 [Config]: bad conversion
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\kernel.cpp:1142 [Kernel]: Rom mapped to address: 0xb0b0000
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\chunk.cpp:136 [Kernel]: Chunk created: ROM, base (in parent): 0x80000000, max size: 0x4193000 type: normal, access: global
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\chunk.cpp:136 [Kernel]: Chunk created: DispatcherTrampolines, base (in parent): 0x84200000, max size: 0x4000 type: normal, access: global
I D:\a\EKA2L1\EKA2L1\src\emu\qt\src\state.cpp:119 [Frontend.Cmdline]: Device being used: Nokia 5320d-1 (01.01) (RM-409)
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:383 [Kernel]: Using general DLL mediaclientaudio_general.dll as patch DLL for map file mediaclientaudio.dll
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:412 [Kernel]: Patch mediaclientaudio.dll.map has no hard requirements
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:421 [Kernel]: Shared section not found for patch DLL mediaclientaudio.dll.map
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:383 [Kernel]: Using general DLL mediaclientaudiostream_general.dll as patch DLL for map file mediaclientaudiostream.dll
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:412 [Kernel]: Patch mediaclientaudiostream.dll.map has no hard requirements
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:421 [Kernel]: Shared section not found for patch DLL mediaclientaudiostream.dll.map
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:383 [Kernel]: Using general DLL scdv_general.dll as patch DLL for map file scdv.dll
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:412 [Kernel]: Patch scdv.dll.map has no hard requirements
T D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:421 [Kernel]: Shared section not found for patch DLL scdv.dll.map
E D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:379 [Kernel]: Can't find suitable patch DLL for map vibractrl.dll
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\chunk.cpp:136 [Kernel]: Chunk created: anonymous1189495134, base (in parent): 0x84300000, max size: 0x63ac type: normal, access: global, anonymous
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:202 [Kernel]: mediaclientaudio_general.dll runtime code: 0x84300000
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:203 [Kernel]: mediaclientaudio_general.dll runtime data: 0x0
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\chunk.cpp:136 [Kernel]: Chunk created: anonymous1940093478, base (in parent): 0x84400000, max size: 0x2ca4 type: normal, access: global, anonymous
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:202 [Kernel]: mediaclientaudiostream_general.dll runtime code: 0x84400000
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:203 [Kernel]: mediaclientaudiostream_general.dll runtime data: 0x0
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\chunk.cpp:136 [Kernel]: Chunk created: anonymous3699205415, base (in parent): 0x84500000, max size: 0x6104 type: normal, access: global, anonymous
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:202 [Kernel]: scdv_general.dll runtime code: 0x84500000
I D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\codeseg.cpp:203 [Kernel]: scdv_general.dll runtime data: 0x0
W D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:259 [Kernel]: Unable to patch export 1 of mediaclientaudiostream_general.dll due to export not exist
W D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:259 [Kernel]: Unable to patch export 4 of mediaclientaudiostream_general.dll due to export not exist
W D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:259 [Kernel]: Unable to patch export 11 of mediaclientaudiostream_general.dll due to export not exist
W D:\a\EKA2L1\EKA2L1\src\emu\kernel\src\libmanager.cpp:259 [Kernel]: Unable to patch export 12 of mediaclientaudiostream_general.dll due to export not exist
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:438 [Service.Applist]: Loading app registries
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Active notes, uid: 0x10281A31
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Search, uid: 0x200044D5
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: GPS data, uid: 0x101F85A0
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Web, uid: 0x10008D39
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Camera, uid: 0x101F857A
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app:  , uid: 0x2000854D
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Cell broadcast, uid: 0x101F4CD3
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Clock, uid: 0x10005903
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Licences, uid: 0x101F85C7
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Groove Labyrinth 2, uid: 0xA0006D8B
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: , uid: 0x1028246E
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Jelly Chase, uid: 0xA0002C40
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Landmarks, uid: 0x101F85A2
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Select language, uid: 0x102832EE
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Landmarks, uid: 0x101F85C1
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Positioning, uid: 0x10281861
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: , uid: 0x102824CD
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Marble Cannon, uid: 0x2000109F
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: RealPlayer, uid: 0x10005A3E
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: , uid: 0x10005A3F
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Dictionary, uid: 0x200159D0
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Search, uid: 0x20000907
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Music player, uid: 0x102072C3
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Music store, uid: 0x101FFB51
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Video sharing, uid: 0x10282391
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: My Nokia, uid: 0x20004F86
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Download!, uid: 0x20007803
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Podcasting, uid: 0x1028190B
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Quickoffice, uid: 0x200002C0
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Adobe Reader, uid: 0x2000745E
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Quickpoint, uid: 0x200002C3
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Quicksheet, uid: 0x200002C2
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Quickword, uid: 0x200002C1
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Radio, uid: 0x10281CB9
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Flash Player, uid: 0x101FD693
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: SIM services, uid: 0x101F4CE0
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Settings, uid: 0x20009B72
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Settings wizard, uid: 0x10281C96
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: , uid: 0x2000BB56
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Share online, uid: 0x2000BB53
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Maps, uid: 0x20001F63
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Phone switch, uid: 0x101FF968
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Video call, uid: 0x101F8681
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: FM radio, uid: 0x101FF976
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: Voice recorder, uid: 0x100058CA
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:254 [Service.Applist]: Found app: 7Days, uid: 0xE534CAFF
E D:\a\EKA2L1\EKA2L1\src\emu\common\src\watcher_win32.cpp:256 [Common]: Can't create directory watch of folder data\drives\d\Private\10003a3f\import\apps\
E D:\a\EKA2L1\EKA2L1\src\emu\common\src\watcher_win32.cpp:256 [Common]: Can't create directory watch of folder data\drives\c\Private\10003a3f\import\apps\
I D:\a\EKA2L1\EKA2L1\src\emu\services\src\applist\applist.cpp:458 [Service.Applist]: Done loading!

**Comment by pent0** [comment]
Please share the SIS if possible. What is the phone language you are setting on emulator

**Comment by LuckyFishGeek** [comment]
> Please share the SIS if possible. What is the phone language you are setting on emulator
language  chinese
https://drive.google.com/file/d/1Gqi9vp0Gh9mqWIK7DFBEdHkWRApKslPX/view?usp=sharing

thanks

**Comment by pent0** [comment]
Hi, it requires me to provide access to the link (is not public). You can upload the file directly here, I can delete on receive.

**Comment by LuckyFishGeek** [comment]
> Hi, it requires me to provide access to the link (is not public). You can upload the file directly here, I can delete on receive.

[tiandidao.zip](https://github.com/EKA2L1/EKA2L1/files/6930464/tiandidao.zip)

**Comment by LuckyFishGeek** [comment]
![Snipaste_2021-08-04_19-04-48](https://user-images.githubusercontent.com/29472751/128170558-a07dc8f4-0548-4114-b784-5db5071c3cd0.png)
The latest version just downloaded or the same error

**Comment by pent0** [comment]
Please wait for the yellow circle on the main page of github emulator to turn to green tick. Thats when building the emulator is done.

**Comment by LuckyFishGeek** [comment]
![Snipaste_2021-08-04_19-36-04](https://user-images.githubusercontent.com/29472751/128174258-85853b1c-59dd-430a-875d-94725f0ae6f4.png)
Fixed thank you

**Comment by LuckyFishGeek** [comment]
@pent0 SMS verification in the game     I also need to trouble again. Thank you.
![Snipaste_2021-08-04_19-56-58](https://user-images.githubusercontent.com/29472751/128176735-d7650049-

**Comment by pent0** [comment]
Please open a new issue. As a workaround, I remember a Chinese person done it already.
