### ISSUE TITLE
Setup Travis CI for build AppImage-package for Linux

### ISSUE THREAD

**Issue by Symbian9** [EKA2L1/EKA2L1#32]
As Appveyor CI already configured for build binary for Windows, let's setup Travis CI for build binary for Linux.

### TODO

- Create file `.travis.yml` (Travis CI configuration script) in the root of `master` branch;
- http://github.com/appimage/appimagekit
  - http://github.com/probonopd/linuxdeployqt
  - http://github.com/probonopd/uploadtool

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by bentokun** [comment]
Anyone want to set up Travis CI and AppImage, feel free to open a PR :D, this is not my top priority right now, but in my TODO list. Note that the UI is written in Lazarus Pascal (I really want to switch to Qt but I don't have time right now), so you have to set up both C++ compiler and Lazarus Pascal for CI.

**Comment by probonopd** [comment]
Can it be compiled on Ubuntu 14.04, are there step-by-step build instructions somewhere that I could literally copy and paste? Then I can send a pull request for making an AppImage.

**Comment by bentokun** [comment]
Yes, with clang, but I think there are many errors when compile with Clang (I was developed this on Ubuntu with Clang before, but now I switch to VS). You need to fix the build errors (if there is), to build this successfully. If you want to pass, tell me :D. 

Build step:
- Look at the appveyor.yml file in root or follow these steps:
- Console executable: Use clang 6.0 (C++ 17 support), create the Makefile using the CMakeLists in the root. Then compile the core using that Makefile. Things are simple as that, that will generate the console executable.
- UI executable: For the UI executable, I will set it up myself base on the AppImage setup for the console executable. The compile part of this is tricky. 
 
Thanks for your help! :D

**Comment by probonopd** [comment]
Once someone can give me the step-by-step build instructions for Ubuntu 14.04 (that I can copy and paste), I can then help to turn it into an AppImage. Thank you very much.

**Comment by williamsthing** [comment]
This is an awful idea.

**Comment by pent0** [comment]
It's implemented now, thanks for the suggestion.

**Comment by probonopd** [comment]
Where can the AppImage be downloaded? I'd like to test it. Thanks!

**Comment by pent0** [comment]
Hi, you can download it in the Releases section of the emulator, its zipped as ubuntu-lastest.zip.
