### ISSUE TITLE
HellStrikerII cannot be verified by SMS

### ISSUE THREAD

**Issue by LuckyFishGeek** [EKA2L1/EKA2L1#320]
**Describe the bug**
Unable to send SMS

**To Reproduce**
After reading the game archive, you need to send an SMS to activate the game, click to confirm and keep sending!

game zip:
[1.zip](https://github.com/EKA2L1/EKA2L1/files/6934921/1.zip)

**Screenshots**
![Snipaste_2021-08-05_07-28-16](https://user-images.githubusercontent.com/29472751/128268480-9cc47fea-fe82-4aa8-921a-6f4e5999d45d.png)

**Your PC or smartphone specs**
- win7 64
- I7-4650U

**Your emulator configuration**
- RM-409, 5320

**Comment by pent0** [comment]
Send the whole file log here, not paste.

This is a non-cracked game, yes?

**Comment by LuckyFishGeek** [comment]
> Send the whole file log here, not paste. (eka2l1.log from folder contains eka2l1.exe)
> 
> This is a non-cracked game, yes?

Cracked game

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6942133/EKA2L1.log)

**Comment by pent0** [comment]
I have checked, the game checked to see if the message is actually in the sent inbox yet, if yes, the game is unlocked. The send API has not communicated with the message inbox API about this yet, so the message did not show up.

I will try to implement this when I can. Let's keep this issue open.

**Comment by pent0** [comment]
When I try the game long ago, I have to resent the message that was unable to send to someone else to unlock the game. How do you do it with this version? I want to gain another perspective to solve this efficiently.

**Comment by LuckyFishGeek** [comment]
> When I try the game long ago, I have to resent the message that was unable to send to someone else to unlock the game. How do you do it with this version? I want to gain another perspective to solve this efficiently.

Thanks for your help I will try to find out if there is another cracked version

**Comment by toiyeuvnd** [comment]
@pent0 are you vietnamese? this game still not have a cracked version yet at the present.

**Comment by pent0** [comment]
Fixed, try again

**Comment by pent0** [comment]
Did it work?

**Comment by LuckyFishGeek** [comment]
> Did it work?

it is work
