### ISSUE TITLE
Add Rendering Resolution

### ISSUE THREAD

**Issue by JaePlays** [EKA2L1/EKA2L1#321]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your PC or smartphone specs**
- OS version
- The CPU you are using
- The GPU you are using

**Your emulator configuration**
- The phone model you are using (RM-409, 5320 Express Music for example)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file

**Comment by TRR95** [comment]
Add Rendering Resolution too vague, we need a description
