### ISSUE TITLE
Changing orientation in game leaves game looking messed up (N-Gage 2.0)

### ISSUE THREAD

**Issue by ayoits0913** [EKA2L1/EKA2L1#322]
So, I tried the latest build, then went in the in-game settings and rotated the device, but this is what I'm left with: 
![Screenshot_1](https://user-images.githubusercontent.com/50942242/128466446-b903f89c-4e01-4c48-9f79-ea15433bed49.jpg)

I'm using Nokia 5320d-1 (01.01) (RM-409 S60v3) as my current device

**Comment by ayoits0913** [comment]
had to relaunch and then it worked. my bad

**Comment by pent0** [comment]
Sorry, is totally ok to keep this. Still a real issue. I will rename accordingly, since this also happens with other games.

**Comment by pent0** [comment]
Please try again with the newest build, it should be fixed

Some trails games that still persists this behaviour, but I can not confirm if it's also like that on real phone, so anyone has issues after this can reopen the issue.

**Comment by pent0** [comment]
No feedback, I will close this, it should be resolved. Thanks for reporting :)
