### ISSUE TITLE
Android: pressing a key on external controller dims the game screen

### ISSUE THREAD

**Issue by fomalsd** [EKA2L1/EKA2L1#323]
**Describe the bug**
Pressing a key on the
I think it's just Android's way of 'focusing' the screen, hence the dimming effect.

**To Reproduce**
1. Connect a wired or bluetooth keyboard/controller (tested with usb keyboard and Xbox One controller)
2. Start an app or game with visible blacks
3. Press a key on the controller
4. See blacks becoming grey on the app screen

**Expected behavior**
Screen dimming shouldn't happen

**Videos**
https://user-images.githubusercontent.com/10403536/128566100-0247d94a-3eaa-4da2-a4d8-c4958ede77ce.mov

**Your PC or smartphone specs**
- Android 11
- Snapdragon 855
- Adreno 640

**Your emulator configuration**
- N-Gage QD

**Comment by nikita36078** [comment]
Could you check out the latest build? I can't reproduce the bug, but tried few things to fix it.

**Comment by fomalsd** [comment]
Didn't help sadly, actually it seemed to break button controls completely – mapped hardware buttons no longer work
https://user-images.githubusercontent.com/10403536/128860865-4ebe3e16-519c-45b5-8f64-dc89fd655133.mov

**Comment by nikita36078** [comment]
Fixed
