### ISSUE TITLE
EKA2L1 Hang after idle

### ISSUE THREAD

**Issue by ramdanirfox** [EKA2L1/EKA2L1#326]
**Describe the bug**
If only EKA2L1 running in the background ( so that no user input happen in the application ), the app suddenly hang after a few minutes. Is it because emulator preceive the phone is about to sleep or into stand by mode I suppose?

**To Reproduce**
1. Open EKA2L1 app
2. Click on some games installed
3. Leave EKA2L1 running in the background or unfocused
4. App hang ( indicated by audio suddenly off )

**Expected behavior**
The app keep running normally, with sound still playing.

**Screenshots**
![image](https://user-images.githubusercontent.com/75406656/129430769-82989bde-dbcb-4cee-85f3-e96a40add33a.png)

**Your PC or smartphone specs**
- Windows 10 update 20H2
- Intel i5 7200U
- Intel HD 620

**Your emulator configuration**
- RH-29 (N-Gage Dev)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6985738/EKA2L1.log)

**Comment by ramdanirfox** [comment]
Hey, i have a trick. If you keep pressing the up button after the game opens and try to change the volume level via windows status bar (while the up button is still pressed), EKA2L1 seems still to receive the up input button right after losing window focus.

But that's not a real solution right?

**Comment by pent0** [comment]
If you scroll down and click on the console, the main emulator freezed is inevitable. Please don't do that. This is with every emulator, you must not block where the emulator dumps their log. (I only know this because of your edits)

I have ran the emulator for about 15mins with low accuracy, running another android emulator and some chrome tabs and it still doing fine with a s60v1 game i haved (SuperMiners).

If you does not do any of the above, you can share a video, I might be able to spot something wrong. Audio popped off is another issue if its specific to this game (if you notice audio run slowdown more and more, it will certainly turn off). I recommend changing the real time accuracy in settings to mid (I will do this as default soon)

**Comment by ramdanirfox** [comment]
> If you scroll down and click on the console, the main emulator freezed is inevitable. Please don't do that. This is with every emulator, you must not block where the emulator dumps their log. (I only know this because of your edits)
No, i didn't do that. I just losing focus of the app. I know it because it also happen when I running Node with blocked text inside console, it no more refresh.

> If you does not do any of the above, you can share a video, I might be able to spot something wrong. Audio popped off is another issue if its specific to this game (if you notice audio run slowdown more and more, it will certainly turn off). I recommend changing the real time accuracy in settings to mid (I will do this as default soon)
It is (by default) 
![eka2l1_qt_pT5OxUYAGT](https://user-images.githubusercontent.com/75406656/129433691-c230fdfc-7bea-46cc-9bdf-e4bef4f1dad7.png)

BTW, it Is not the latest build.

**Comment by pent0** [comment]
> If you does not do any of the above, you can share a video

I'm as clueless as you are...

> BTW, it Is not the latest build.
I don't understand why you want to report old build issue. Please update. Based on the log, the build you use is 22 days ago

**Comment by ramdanirfox** [comment]
Hehe, sorry about that. I will try again with latest build.

I will tell whether the issue persist or not.

**Comment by ramdanirfox** [comment]
> Hi, if this is not fixed you can tell me. I will take a test again.

Oh, i'm sorry about that. Last time i tried to record it with OBS Studio right after you requested, but the crash didn't occur. It seems crash happen randomly but rare. I might try it again tommorow with latest version.
