### ISSUE TITLE
[help]n-gage2 platform can run by vivo y93s。but redmi3s can't run。

### ISSUE THREAD

**Issue by fuzfu** [EKA2L1/EKA2L1#329]
as the title。
install the Software：
eka2l1 v0.0.6

rom:
5320（0501）.rom
5320（0501）.rpkg

sis Software:
N-Gage 2.0 v1.40.1557 by BodyZ, Fixed by FROST_A-52.sis

change file:
config.yml(888B)
[content:
(ui-scale: 1
bkg-alpha: 129
bkg-path: ""
font: ""
log-read: false
log-write: false
log-ipc: false
log-svc: false
log-passed: false
log-exports: false
cpu: dynarmic
device: 0
language: 1
emulator-language: -1
enable-gdb-stub: false
data-storage: data
gdb-port: 24689
enable-srv-ecom: false
enable-srv-cenrep: true
enable-srv-backup: true
enable-srv-install: true
enable-srv-rights: true
enable-srv-sa: true
enable-srv-drm: true
enable-srv-eikappui: true
enable-srv-akn-icon: false
enable-srv-akn-skin: true
enable-srv-cdl: false
enable-srv-socket: true
fbs-enable-compression-queue: false
accurate-ipc-timing: false
enable-btrace: false
stop-warn-touchscreen-disabled: false
dump-imb-range-code: false
hide-mouse-in-screen-space: false
enable-nearest-neighbor-filter: true
integer-scaling: true
cpu-load-save: true
rtos-level: ""
ui-new-style: true
cenrep-reset: true
imei: 540806859904945
)]

phone:

vivo y93s:
cpu:mtk mt6762
Memory:4g+128g
system:funtouch os(Android 8.1)

redmi3s:
cpu:Qualcomm Snapdragon 430
Memory:3g+32g
system:miui10 9.3.28Development version os（Android 6.0.1)

vivo y93s can run the n-gage2 platform and run the game of "Hooked.On.Creatures.of.the.Deep" and all go well。happying!

so what!!when use the redmi3s,oh!no!the n-gage2 platform can't jump in!!!it jump out!!sadding!!
the system give out the bug information :
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/9.3.28:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 24722, tid: 24751, name: RxCachedThreadS  >>> com.github.eka2l1 <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x55983bb490
Abort message: 'C ../../../../../../kernel/src/svc.cpp:1222 [Kernel]: Leave started! Guess leave code: -1
'
    x0   00000055983bb4a0  x1   0000007f521aef58  x2   0000000000000001  x3   00000055983bb500
    x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
    x8   00000055983bb490  x9   a4a2f2e4c5a3ae30  x10  0000000000000003  x11  0000000000004000
    x12  0000007f77fe2b98  x13  0000005598b93a20  x14  0000005595f72000  x15  0000007f77fe2af8
    x16  0000007f77fdba58  x17  0000000000000000  x18  0000000000000008  x19  0000007f521aef58
    x20  0000005598032cf0  x21  00000055971a1fe0  x22  00000055983bb4a0  x23  00000055971a1fe0
    x24  0000007f521aee71  x25  0000007f60f3e320  x26  0000007f521aef70  x27  0000000000000000
    x28  0000007f5fa69010  x29  0000007f521aee00  x30  0000007f606fbbbc
    sp   0000007f521aedd0  pc   00000055983bb490  pstate 0000000060000000

backtrace:
    #00 pc 00000000020db490  [heap]
    #01 pc 0000000000641bb8  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l14epoc20window_server_client16execute_commandsERNS_7service11ipc_contextENSt6__ndk16vectorINS_6ws_cmdENS5_9allocatorIS7_EEEE+60)
    #02 pc 0000000000641aa4  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l14epoc20window_server_client20parse_command_bufferERNS_7service11ipc_contextE+284)
    #03 pc 0000000000647e64  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l113window_server22send_to_command_bufferERNS_7service11ipc_contextE+92)
    #04 pc 00000000005bdf60  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l17service6server20process_accepted_msgEv+612)
    #05 pc 0000000000565060  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so
    #06 pc 000000000057ad38  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZNSt6__ndk110__function6__funcIZN6eka2l13hle6bridgeINS2_13kernel_systemEiJjiPKjNS2_3ptrINS2_4epoc14request_statusEEEEEEDaPFT0_PT_DpT1_EEUlPS5_PNS2_6kernel7processEPNS2_3arm4coreEE_NS_9allocatorISQ_EEFvSJ_SM_SP_EEclEOSJ_OSM_OSP_+152)
    #07 pc 0000000000535624  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l13hle11lib_manager8call_svcEj+600)
    #08 pc 000000000055289c  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so
    #09 pc 000000000096b858  /data/app/com.github.eka2l1-1/lib/arm64/libnative-lib.so (_ZN6eka2l13arm22dynarmic_core_callback7CallSVCEj+56)
    #10 pc 000000000005bec4  <unknown>

I Lose your mind!(>_<)!!Can the developers show me the way?
I very like to play the game of "Hooked.On.Creatures.of.the.Deep"。I wait for that for very more times。but it can't run on my phone style!!

by the way，I feel apologetic of my poor English。I hope the developers can mean my words。best wish for this geat projects。

**Comment by pent0** [comment]
I think I enter this same issue on my phone, if there is any progress on the fix or more information needed I will let you know! Very sorry if the wait time will be long. You can use a translator like DeepL to produce easy readable english.

**Comment by fuzfu** [comment]
> I think I enter this same issue on my phone, if there is any progress on the fix or more information needed I will let you know! Very sorry if the wait time will be long. You can use a translator like DeepL to produce easy readable english.
