### ISSUE TITLE
The screen of "Prince of Persia HD" will be blurred.

### ISSUE THREAD

**Issue by sniperhgy** [EKA2L1/EKA2L1#337]
Dear developer of EKA2L1, I tried to execute a S60V3 game "Prince of Persia HD" in EKA2L1, the screen will be blurred.

OS : Windows 10
Env : LDPlayer 3.121
Ver : Latest version of EKA2L1 for android.
Rom : Nokia 5320d-1 (05.01), vertical version.

![Capture](https://user-images.githubusercontent.com/13534439/135738815-196b488f-0512-4841-8a33-cc982e3dfe84.JPG)

**Comment by quocbao2002** [comment]
hello bro. Can you tell me what rom you're using for this game?

**Comment by quocbao2002** [comment]
oh. You are using 5320 rom

**Comment by quocbao2002** [comment]
try to download this game from here and try again
http://dedomil.net/games/3887/download/53359
remember deleted old version before doing this

**Comment by sniperhgy** [comment]
@quocbao2002 Hello, sorry for the delayed response. Sure, I'm using Nokia 5320's rom, will take a shot on your link then reply to you. Thank you for all the information.

**Comment by sniperhgy** [comment]
@quocbao2002 Hi, I take a shot on your link, it works properly, thank you very much. It seems this ticket could be closed.
