### ISSUE TITLE
Huawei mate40 upgrade HarmonyOS after opening the N-Gage 2.0 white screen

### ISSUE THREAD

**Issue by huchao2007** [EKA2L1/EKA2L1#342]
Huawei mate40 upgrade HarmonyOS after opening the N-Gage 2.0 white screen, hoping to be resolved by the authorities

**Comment by pent0** [comment]
Thank you, were you using 5320 to run the n-gage or another emulated device?

**Comment by huchao2007** [comment]
5320 Chinese firmware发自我的华为手机

**Comment by huchao2007** [comment]
5320 Chinese firmware

**Comment by pent0** [comment]
Okay, Im still unclear of how this happen, but the log has located the crash function, so I will look soon.

**Comment by pent0** [comment]
Please check out a new release 30 minutes from the time of posting this comment, it should be fixed.
