### ISSUE TITLE
Xbox Wireless Controller DPad left not registered.

### ISSUE THREAD

**Issue by ZZZXXX0110** [EKA2L1/EKA2L1#348]
**Describe the bug**
Xbox Wireless Controller DPad left button is not registered by the emulator in the settings, and thus cannot be used with any game

**To Reproduce**
1. Go to settings and go to Control.
2. Attempt to bind Xbox Wireless Controller DPad left button to any of the keys.
3. Watch and see nothing happens when pressing Xbox Wireless Controller DPad left button while the emulator is waiting for input.

**Expected behavior**
Xbox Wireless Controller DPad left button can be assigned and bound in the emulator just like every other buttons on this controller.

**Your PC or smartphone specs**
- OS version: Windows 11 Pro Insider Preview build 22489.1000
- The CPU you are using: i7-8650U
- The GPU you are using: Intel UHD Graphics 620

**Your emulator configuration**
This problem occurs regardless of the phone model, installing different phone devices do not make difference. In fact, this problem occurs even when trying to change controller key bindings before installing any emulated device at all.
Build tested: aa0e34f38

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file
-
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/7465084/EKA2L1.log)

**Comment by pent0** [comment]
In todo, duplicated with #346
