### ISSUE TITLE
App freezing playing Rifts

### ISSUE THREAD

**Issue by grav1tyzero** [EKA2L1/EKA2L1#357]
**Describe the bug**
App keeps freezing playing Rifts - promise of power

**To Reproduce**
go to Rainetown
wait for combat to start
attack enemy
game usually freezes by then

**Expected behavior**
the game to continue to play

**Screenshots**
![image](https://user-images.githubusercontent.com/94650741/142504090-204eff15-7410-4ae1-9451-751cbcf9e490.png)

**Your PC or smartphone specs**
- Windows 10
- Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz   3.50 GHz
- onboard video

**Your emulator configuration**
- Nokia N-Gage QD Dev (RH-29, 5320 S60v1)

**Log**
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/7566390/EKA2L1.log)

**Comment by grav1tyzero** [comment]
forgot to add the console window, the line colored in red:
 D:\a\EKA2L1\EKA2L1\src\emu\services\src\fs\files.cpp:772 [Service.EFsrv]: Trying to open a non-existence file: c:\system\apps\6R49\RiftsSingle3 while the open mode requires its availbility!

shows up every time it freezes.  also non-existence is a typo.

![image](https://user-images.githubusercontent.com/94650741/142511159-35cfcd62-5753-4ee5-bffa-46ccfc76ac19.png)

**Comment by pent0** [comment]
Im very in doubt the emulator has anything to do with this at a specific point at this stage of s60v1 emulation, if you can confirm it does not happen on a real phone, I will fix. Also thanks! I will fix the typo

**Comment by grav1tyzero** [comment]
Alrighty, will probably be a couple months to source a good condition one
and a copy of the game. Just thought it was weird that it only freezes on
that particular map, and does so no matter the weapon or character
configuration haha. Thanks for taking the time to look into it.

**Comment by pent0** [comment]
If you can provide me with save folder, C:/system/apps/6r49, I can try to see if I can detect any emulator fault, thanks! I probably said the upper comment too soon.

**Comment by pent0** [comment]
Seems to be in inactivity, sorry for not helping much！I will close it for now
