### ISSUE TITLE
Error: Unimplement system call: 0xC00026

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#358]
Not a lot to say, there are 6 so far games that give this error, most of them don't run.

Astro Quest 
Twin Fruits 
Rons Adventure
Joes Treasure Quest 3D
Cricket 3D
Cybersaurus

**Comment by pent0** [comment]
Check again when 5010c2f is available. It appears in all games, not just these games, not life-threatening, but I agree that it needs to be silent.
