### ISSUE TITLE
If I set the fps for a game to 0 the game crashes and I have to change it manually

### ISSUE THREAD

**Issue by piegit** [EKA2L1/EKA2L1#361]
**Describe the bug**
If I set the fps for a game to 0 the game crashes and I have to change it manually

**To Reproduce**
1. Open a game
2. Go to general
3. Change the fps to 0

**Expected behavior**
Don't let the fps go to 0 or put a menu up asking if you want to do that.

**Screenshots**

**Your PC or smartphone specs**
- Windows 11
- Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz, 3001 Mhz, 4 Core(s), 4 Logical Processor(s)
- Nvidia 1060GTX 3GB

**Your emulator configuration**
- Nokia N-Gage (NEM-4 - S60v1)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/7575162/EKA2L1.log)

**Comment by pent0** [comment]
Thats very fair, I will fix it soon, thanks for  the report.

**Comment by pent0** [comment]
It should be fixed in the newest release, please check in 30 minutes from this message.

**Comment by pent0** [comment]
Assume to be solved
