### ISSUE TITLE
Head2Head Streetracing: Missing Icon

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#362]
Head2Head Streetracing is missing its icon

https://media.discordapp.net/attachments/703563521379663883/910428437259382824/Capture.JPG?width=621&height=646

**Comment by Ink321** [comment]
Everything works with this icon.
![6](https://user-images.githubusercontent.com/70818773/143283675-25b167ab-8f3d-4217-bf04-010637179995.png)
[H2H.zip](https://github.com/EKA2L1/EKA2L1/files/7597578/H2H.zip)
