### ISSUE TITLE
Invalid Ordinal Errors

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/EKA2L1#365]
I'm running into many Invalid ordinal errors

Cricket3D
[Kernel]: Invalid ordinal 296, requested from EikCore.dll

Bamboo Dance
[Kernel]: Invalid ordinal 2331, requested from avkon.dll
[Kernel]: Invalid ordinal 328, requested from CONE.DLL
[Kernel]: Invalid ordinal 1222, requested from EikCoctl.dll

Football Pro Contest
[Kernel]: Invalid ordinal 2677, requested from avkon.dll
[Kernel]: Invalid ordinal 295, requested from EikCore.dll
[Kernel]: Invalid ordinal 296, requested from EikCore.dll

**Comment by pent0** [comment]
If wrong ordinal, you have used the wrong OS version for the game. Newer OS versions can have new API functions (ordinal) that are not available on older OS, and some apps may target specifically s60v2
