### ISSUE TITLE
Crash when using CLI --fullscreen together with --app 0x12345678

### ISSUE THREAD

**Issue by TrojanBarber** [EKA2L1/EKA2L1#366]
eka2l1_qt.exe --fullscreen --app 0x101fd3f6
crashes emulator and quits to desktop.

eka2l1_qt.exe --app 0x101fd3f6
works correctly and launches game in window... after that, CTRL+F goes to fullscreen without problem... and game is fully playable :)

Tested on Automatic CI build: master-a0784701e

**Comment by pent0** [comment]
Thank you, I have received this issue, will notify you when it's fixed

**Comment by pent0** [comment]
It should be fixed now, please try when possible。 I'll close the issue in a week if there's no respone, thank you for waiting!

**Comment by TrojanBarber** [comment]
It is working now.
Thank you very much :)

**Comment by pent0** [comment]
Thanks!
