### ISSUE TITLE
Feature request, upscaling

### ISSUE THREAD

**Issue by xlen** [EKA2L1/EKA2L1#389]
While playing around with games I've noticed that the low resolution is an issue with the gaming experience and well nearest neighbor filtering isn't really enough, maybe something more complex such as FSR could clean up the image.
This might be helpful:
https://gist.github.com/atyuwen/78d6e810e6d0f7fd4aa6207d416f2eeb#gistcomment-3873212

**Comment by pent0** [comment]
Sorry for the late respone, thanks a lot! I will try to apply for a post processing shader like this.

**Comment by pent0** [comment]
There's already an existing issue like this, I will move your comment to it (cc #376 )
