### ISSUE TITLE
How can I provide .rom and .rpkg file

### ISSUE THREAD

**Issue by veso266** [EKA2L1/EKA2L1#394]
**Describe the bug**
Hello there, here: https://eka2l1.miraheze.org/wiki/Nokia_Devices
I read that .rom file exists (although I don't  know where so I could download it) but .rpkg file is missing for this model

I have Nokia E63 (its Patched and has X-Plore and I was wondering how can I dump .rpkg file from it so I can provide it here

Thanks for Anwsering and Best Regards

**Comment by yfaizin1** [comment]
How to created ROMs https://youtu.be/4FpIUV2wDE8

Pada tanggal Kam, 3 Mar 2022 5.30 PM, veso266 ***@***.***>
menulis:

**Comment by veso266** [comment]
Here you go, as per instructions: https://youtu.be/IewQOLfFDOE

https://transfer.sh/CYQhTe/romdumpplus.dmp
https://transfer.sh/AS6RaV/superpage.dmp

Now, how do I extraxt .rom and .prg file from theese so I can load them into EKA2L1?

Also where can I download some other phone roms? (I read on the wiki that roms are uvailable but I could not find them)

Also if anyone knows, how could I sign apps for this phone (or at least get dev certificate for its IMEI, that would be great) nowadays (yea this one is patched but would still like to sign an app to install on an unpatched phone)

**Comment by pent0** [comment]
Check the wiki please, there's a section for that !
