### ISSUE TITLE
Games from 3DArtMobile

### ISSUE THREAD

**Issue by VoPavel** [EKA2L1/EKA2L1#396]
It is still not possible to play a single game from 3DArtMobile on any rom.  Alien Pinball, Soccer Pinball, ....

[android.log](https://github.com/EKA2L1/EKA2L1/files/8239594/android.log)
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/8239595/EKA2L1.log)

**Comment by pent0** [comment]
Please follow the issue template and post log please. I won't try all the games you say at the moment, but I can look into and try to fix if the bug is small. Edit your issue, I will look again in few days!

**Comment by VoPavel** [comment]
Why are new versions of the emulator built just for specific games?  I played this enthusiastically, and in the new versions it doesn't work again. 🙁🙁🙁🙁

https://youtu.be/yB6f-xcZreE

**Comment by TRR95** [comment]
> 

No, its not made for specific games, Symbian is complex and there is still a lot we don't understand about it. there are many games that I would like to try but can't because of some unknown reason, 3DArtMobile game will be playable one day but for now, there not.

**Comment by TRR95** [comment]
The data forum is completely unfilled out

**Comment by yeatse** [comment]
Fixed on latest build
