### ISSUE TITLE
Resident evil degeneration ngage 2.0 force close on newest build

### ISSUE THREAD

**Issue by kenobizero** [EKA2L1/EKA2L1#398]
The games work on previous build 0.0.4 but update version doesn't
The specs phone
32 bit android 7.0 samsung j7 prime exynos 7870

**Comment by pent0** [comment]
Hi, please check lastest Automatic Release !

**Comment by kenobizero** [comment]
![Screenshot_20220420-191129_EKA2L1](https://user-images.githubusercontent.com/73557739/164227768-c43744cb-5310-46d2-bbc6-7231e139c0f2.jpg)
It crashed sir with newest build

**Comment by kenobizero** [comment]
fixed thanks for update i will close this issue
