### ISSUE TITLE
最高通缉进入游戏一会自动退出

### ISSUE THREAD

**Issue by cong1985** [EKA2L1/EKA2L1#400]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your PC or smartphone specs**
- OS version
- The CPU you are using
- The GPU you are using

**Your emulator configuration**
- The phone model you are using (RM-409, 5320 Express Music for example)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file

**Comment by MTPxD** [comment]
what?

**Comment by gonejack** [comment]
Translation: 

High Seize crashes.

**Comment by TRR95** [comment]
The title is in another language and the date forum is completely unfilled out
