### ISSUE TITLE
When I clicked 'eka2l1_qt.exe' file, the file msvcp140_1.dll was missing

### ISSUE THREAD

**Issue by MTPxD** [EKA2L1/EKA2L1#405]
**Describe the error**
When I installed a latest version and clicked eka2l1_qt.exe file, the msvcp140_1.dll was missing on my computer,
even I try to add the msvcp140_1.dll file on https://www.dll-files.com/msvcp140_1.dll.html, still didn't work correctly.

**Screenshots**
![Error1](https://user-images.githubusercontent.com/89562751/163080580-9ca3666e-c9e8-4a49-af06-cd2b4e319448.png)
![Error2](https://user-images.githubusercontent.com/89562751/163080599-6808e636-5ab0-4b88-abfe-ba215b656ac4.png)

**PC specs**
- OS version: Windows 7
- The CPU I am using: Intel Core i3-6100 (3,70GHz)
- The GPU I am using: Intel HD Graphic 530

**Emulator configuration**
- Nokia 5320d-1 (05.01) [RM-409]

**Log**
- No log included.

**Comment by pent0** [comment]
Hi, please follow this link here and install components, never download .dll file and copy them in general. They may contain visit. https://12z1.com/download/#note-for-windows

**Comment by pent0** [comment]
I assume this is resolved

**Comment by MTPxD** [comment]
> 

thanks dude it worked! :D
![Resolved](https://user-images.githubusercontent.com/89562751/164146133-5677a92f-a497-42da-87d6-1776e22498ef.png)
