### ISSUE TITLE
Error executing script entry of gof_red_fix: [string "gof_red_fix"]:24: attempt to index global 'gofExecSeg (a nil vaule)

### ISSUE THREAD

**Issue by MTPxD** [EKA2L1/EKA2L1#406]
**Describe the bug**
I seen on the Terminal of EKA2L1, I seen this message:
*E D:\a\EKA2L1\EKA2L1\src\emu\script\src\manager.cpp:336 [Scripting]: Error executing script entry of gof_red_fix: [string "gof_red_fix"]:24: attempt to index global 'gofExecSeg (a nil vaule)*
When I clicked on Symbian's application, it not respondable.
Someone fix it dude. :-/

**Screenshots**
![Another error](https://user-images.githubusercontent.com/89562751/164148083-60957227-a319-4862-a5e7-4238f944683d.png)

**PC specs**

OS version: Windows 7
CPU: Intel Core i3-6100 (3,70GHz)
GPU: Intel HD Graphic 530

**Emulator configuration**

Nokia 5320d-1 (05.01) [RM-409]

**Log**

No log included.

**Comment by pent0** [comment]
Script removed! Thanks
