### ISSUE TITLE
Angry birds rio make log file size go bruhhhhhhhh

### ISSUE THREAD

**Issue by D-06** [EKA2L1/EKA2L1#411]
I don't know why but while checking the log file eka2l1.log file size go too much high(running only 1- 5 minute and already 677MB)
Edit : huh try other game and it return to few kb( game i test is angry bird rio)

**Comment by D-06** [comment]
Delete and try again on 1 minute
![Screenshot_20220510-135617_X-plore](https://user-images.githubusercontent.com/82329926/167566928-513e07a8-76be-475f-97f4-5030e93cba73.jpg)

**Comment by pent0** [comment]
Recheck

**Comment by pent0** [comment]
I will close on inactivity
