### ISSUE TITLE
Mac os12

### ISSUE THREAD

**Issue by Shimmer2** [EKA2L1/EKA2L1#412]
I can't open any apps on the Mac os 12, with n82,5700,5730,5320, E72i, and the seven days game can't open normally.When quitting the program, the program crashes and can only force the exit
![D92739BB-D845-40A9-B471-25E64F083D5B](https://user-images.githubusercontent.com/79088619/169628760-b34adc77-4f0c-4e8e-916a-a2b90bee764a.jpeg)
![F66898F0-1BF6-446E-B7D7-6F0DDCCC0B46](https://user-images.githubusercontent.com/79088619/169628770-7b15d81e-56ee-40d2-8ce0-70efcf3ff60f.jpeg)

**Comment by pent0** [comment]
Will resolve it in newer issue!
