### ISSUE TITLE
Error in mshell

### ISSUE THREAD

**Issue by zixing131** [EKA2L1/EKA2L1#421]
r: 0x49, fake return with epoc::error_none
E D:\a\EKA2L1\EKA2L1\src\emu\services\src\window\classes\wingroup.cpp:323 [Service.Window]: Unimplemented window group opcode 0x30!
W D:\a\EKA2L1\EKA2L1\src\emu\services\include\services/context.h:102 [Service.Track]: Getting packed struct with mismatch size (72 vs 64), size to get will be automatically clamped
E D:\a\EKA2L1\EKA2L1\src\emu\services\src\socket\connection.cpp:74 [Service.Esock]: Unimplemented socket connection opcode: 67

**Comment by TRR95** [comment]
this issue is currently invalid, there is not enough info like

What platform are you trying to play this game on?
What Rom you're using?
A log file needs to be uploaded
