### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by soaresden** [EKA2L1/EKA2L1#431]
**Describe the bug**
Can't connect to github message.

**To Reproduce**
1. Try to update from the menu

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54243866/185609353-399c96d9-5f96-40fc-9502-04529a03d6e4.png)

**Your PC or smartphone specs**
- OS version
- The CPU you are using
- The GPU you are using

**Your emulator configuration**
- The phone model you are using (RM-409, 5320 Express Music for example)

**Log**
- Attach your log file (EKA2L1.log), which is in same directory as your executable file
- [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/9381768/EKA2L1.log)

**Comment by soaresden** [comment]
fixed in https://github.com/EKA2L1/EKA2L1/commit/2b325212e85bf077bd91115295995faa46772a08

**Comment by Tetriser** [comment]
![image](https://user-images.githubusercontent.com/5746458/230689384-e46c2508-0b3f-4916-8ab9-718ada3f5d38.png)
Latest version, same problem
