### ISSUE TITLE
Gof Red Fix at launch

### ISSUE THREAD

**Issue by soaresden** [EKA2L1/EKA2L1#433]
Not a new issue apparently : https://github.com/EKA2L1/EKA2L1/issues/406 
But I will try to complete this one with my logs and stuff

![image](https://user-images.githubusercontent.com/54243866/186739106-4341caac-648a-49b6-a6db-29d92f51d3a0.png)
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/9427316/EKA2L1.log)

It's been there almost for a year.
I don't think it's a big issue, since it seems that everything is working but this message in red still keep my attention x) !

**Comment by pent0** [comment]
Ah, this script has been removed on build, but still exist locally (the emulator did not delete it itself). You can safely remove it in scripts folder. Sorry!
