### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by necros2k7** [EKA2L1/EKA2L1#435]
[Z:/EKA2L1-master/src/emu/common/src/hash.cpp:24] (performance) Parameter 'to_remove' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/common/src/algorithm.cpp:45] (performance) Parameter 'targ' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/common/src/algorithm.cpp:45] (performance) Parameter 'str' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/common/src/algorithm.cpp:55] (performance) Parameter 'to_remove' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/dispatch/src/libraries/gles1/shadergen.cpp:254] (performance) Parameter 'source' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/dispatch/src/libraries/gles1/shadergen.cpp:286] (performance) Parameter 's1' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/dispatch/src/libraries/gles1/shadergen.cpp:286] (performance) Parameter 's2' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/dispatch/src/libraries/gles1/shadergen.cpp:286] (performance) Parameter 's3' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
[Z:/EKA2L1-master/src/emu/qt/src/updater.cpp:114] (performance) Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]
[Z:/EKA2L1-master/src/emu/vfs/src/vfs.cpp:501] (performance) When an object of a class is created, the constructors of all member variables are called consecutively in the order the variables are declared, even if you don't explicitly write them to the initialization list. You could avoid assigning 'iterator' a value by passing the value to the constructor in the initialization list. [useInitializationList]

**Comment by TRR95** [comment]
this issue is currently invalid, there is not enough info like

What platform are you trying to play this game on?
What Rom you're using?
A log file needs to be uploaded
