### ISSUE TITLE
Switching devices leads to stuck

### ISSUE THREAD

**Issue by denjhang** [EKA2L1/EKA2L1#444]
I use preconfigured packages. Every time I switch devices it crashes eka2l1. I need to forcibly close eka2l1 and reopen it, the device I switched last time will appear.
![sshot-20221023-184216](https://user-images.githubusercontent.com/61811583/197387955-00094c89-ee90-41af-a536-846e2e288bbc.png)

**Comment by pent0** [comment]
I will close this issue on no-feedback. I will gradually fix the crashes!
