### ISSUE TITLE
Compilation error in the current automatic build?

### ISSUE THREAD

**Issue by ZZZXXX0110** [EKA2L1/EKA2L1#447]
**Describe the bug**
In the current latest automatic build that corresponds to commit 9051a1d, downloaded with the "[windows-latest.zip](https://github.com/EKA2L1/EKA2L1/releases/download/continous/windows-latest.zip)" file, when launching any game the emulator window immediately freezes with no new window popping up. When closing the emulator window, an error appears in the console window: 

```
D:\a\EKA2L1\EKA2L1\src\emu\drivers\src\graphics\backend\ogl\graphics_ogl.cpp:1877 [Driver.Graphics]: Corrupted graphics command list! Emulation halt.
```

It is however worth noting that I do NOT have a "D:\a\EKA2L1\EKA2L1\src\emu\drivers\src\graphics\backend\ogl\" folder at all, my EKA2L1 files are stored in "D:\EKA2L1\". Also I assume the file that's invoked by the rendering system shouldn't be just lose .cpp files containing the source code? 

I'm guessing this might be a compilation problem.

**To Reproduce**
1. Attempt to launch a game
2. See error

**Expected behavior**
Game launches as normal with no error in the console window.

**Your PC or smartphone specs**
- Windows 11 build 22621.819
- CPU: i9-10980HK
- GPU: RTX2070 Super, driver version 526.47
- (Intel iGPU disabled and physically bypassed via laptop's mux switch).

**Your emulator configuration**
- N95 (RM-320 - S60v3 FP2) included in the pre-compiled package, also tested E5 (RM-632) rom I installed myself before, same error.

**Log**
- The log contains exactly one single line:
```
E D:\a\EKA2L1\EKA2L1\src\emu\drivers\src\graphics\backend\ogl\graphics_ogl.cpp:1877 [Driver.Graphics]: Corrupted graphics command list! Emulation halt.
```

**Comment by HAKODEVx** [comment]
yeah same
