### ISSUE TITLE
Micropool s60v1 and s60v2 return 2023

### ISSUE THREAD

**Issue by danik206** [EKA2L1/EKA2L1#460]
. Well me today not long ago 2021-2023 Why not update the MicroPool game on s60v1 and s60v2 Please kindly fix the game here is this picture that does not work Micropool
![Screenshot_20230123-193648](https://user-images.githubusercontent.com/78295547/214110715-a2a0e475-378e-4538-bb86-7d841d6835b7.png)
![Screenshot_20230123-193653](https://user-images.githubusercontent.com/78295547/214110727-bdd349cc-0732-4e5f-8e2b-0e7972d264a4.png)

**Comment by pent0** [comment]
Fixed, recheck please!
