### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#47]
Keep track of states load and save for these objects:

### Kernel object
  - [ ] Chunk (Missing load data)
  - [ ] Semaphore
  - [ ] Change notifier
  - [ ] Library
  - [ ] Mutex

### System
  - [ ] Timing

### Services
  - [ ] File Server
  - [ ] Posix Server (Per Process)

The plan:
- A pointer wrap object, wrapping save and load in only one function. The pointer wrap will tells us if we are in read or write mode.
- Can highlight section to check for valid save file. Example, if we save/load the "Timing" section, the "Timing" string must be written/available.

**Comment by pent0** [comment]
Not planned anymore

**Comment by TRR95** [comment]
Reopened because save states is a common feature, new tags will inform people where it stands
