### ISSUE TITLE
Change the AppImage name to something more specific?

### ISSUE THREAD

**Issue by leonstyhre** [EKA2L1/EKA2L1#509]
Hi!

Would it be possible to change the name of the AppImage to something more specific? For example EKA2L1.AppImage instead of ubuntu-latest.AppImage?

It's good that you don't put version information in the AppImage filename, this way a frontend can easily download the latest version and it will still be easily found on game launch, but when mixing many AppImages in the same directory it's really good if they are all distinctly named so it's clear which AppImage is for which emulator.

Thanks!

**Comment by XargonWan** [comment]
Greetings, I'm Xargon from RetroDECK and we would like to have this issue addressed because we aim to ship EKA2L1.
Thanks in advance.

**Comment by pent0** [comment]
Sorry for the late response, I don't check issues much but communicate on Discord more. I assume you want to change the appimage file name? If so an edit to the CI file should just do it. I dont know how your update pipeline work so I will not make any assumption on why you guys cant rename it yourself that is what you mean.

**Comment by leonstyhre** [comment]
Thanks for looking into this! I think it's good practice to have a more descriptive name. It's also good practice to not include version info into the AppImage filename so that it stays consistent across releases.

Most projects simply add the architecture to the filename, so if you want to do something similar maybe something like the following could be good candidate?

EKA2L1-x86_64.AppImage

**Comment by pent0** [comment]
Yeah sure, no problem. I dont have anything against that if that helps you.
I will edit it and see through other issues when I can.

Vào 18:13, Th 2, 1 thg 4, 2024 Leon Styhre ***@***.***> đã
viết:

**Comment by leonstyhre** [comment]
Great, thanks :)
