### ISSUE TITLE
Pressing the 'L' key should confirm actions within the game, not exit it.

### ISSUE THREAD

**Issue by roseclarkh** [EKA2L1/EKA2L1#510]
**Describe the bug**
In the Android version of the EKA2L1 emulator, after installing and attempting to play the game "七夜" (7Days), there's a malfunction with the 'L' key. The 'L' key is supposed to confirm actions, but instead, pressing it exits the game and returns to the main screen.

**To Reproduce**
1. Launch the EKA2L1 emulator.
2. Start the game "七夜" (7Days).
3. In the game, try to perform an action that requires the 'L' key for confirmation, such as sending a registration text message.
4. See error: The game exits and returns to the main screen.

**Expected behavior**
Pressing the 'L' key should confirm actions within the game, not exit it.

**Screenshots**
no

**Your PC or smartphone specs**
- OS version: Android

**Your emulator configuration**
- 5320

**Log**
- no

**Comment by pent0** [comment]
5320 rom has a bug where if the menu is empty (no content) it crashed . I gurantee you, this also happens on a real phone. You can find s60v3 fp2 device to run it, as s60v3 fp1 rom all have this problems
