### ISSUE TITLE
Feature: Allow loading games from a frontend (e.g. Daijishou)

### ISSUE THREAD

**Issue by andiweli** [EKA2L1/EKA2L1#514]
EKA2L1 doesn't allow loading roms from a frontend.
Please can you implement this feature.

Thanks

**Comment by pent0** [comment]
I added the support, on newest Github or PlayStore version, you can hold the game in menu and choose "Create launch file". It will save the game you want to play as ROM to a folder you choose. Then you can create a platform in your frontend (for example, daijisho), and choose the ROM folder you save the game to.

[Video demo link](https://cdn.discordapp.com/attachments/1132960347448418367/1208843634146021446/Screenrecorder-2024-02-19-01-07-26-796.mp4?ex=6609ac5d&is=65f7375d&hm=5f79e2169c78e106762511bba7642792694d23feb745cd04d265e16ea55f06ca&)

I recorded video of me importing games to daijisho. You can try it first , if you feel something need to change or you have problems, i can help (in Discord, sorry).... Launch command format is in video (at 1:00). ROM extension is .json

**Comment by andiweli** [comment]
Thanks. Sadly I can test because the Logitech G Cloud Console I am using doesn't show any N-Gage games when loading. 

Is the emulator compatible with Snapdragon/Adreno?

**Comment by andiweli** [comment]
@pent0 took a while, but i managed to get it working with the new launcher files in json format. not with daijishou, but with beacon game launcher. works like a charm 👍🏻

![image](https://github.com/EKA2L1/EKA2L1/assets/11447150/06cae457-aeec-45eb-9749-a71564da14e3)

**Comment by Starman99x** [comment]
> I added the support, on newest Github or PlayStore version, you can hold the game in menu and choose "Create launch file". It will save the game you want to play as ROM to a folder you choose. Then you can create a platform in your frontend (for example, daijisho), and choose the ROM folder you save the game to.
> 
> [Video demo link](https://cdn.discordapp.com/attachments/1132960347448418367/1208843634146021446/Screenrecorder-2024-02-19-01-07-26-796.mp4?ex=6609ac5d&is=65f7375d&hm=5f79e2169c78e106762511bba7642792694d23feb745cd04d265e16ea55f06ca&)
> 
> I recorded video of me importing games to daijisho. You can try it first , if you feel something need to change or you have problems, i can help (in Discord, sorry).... Launch command format is in video (at 1:00). ROM extension is .json

How to do this in the PC version?
