### ISSUE TITLE
git submodules (dynarmic-android and ext-boost) are not available

### ISSUE THREAD

**Issue by roma-jam** [EKA2L1/EKA2L1#527]
**Describe the bug**
Git submodules not available

**To Reproduce**
1. `$ git clone git@github.com:EKA2L1/EKA2L1.git`
2. `$ git submodule update --init --recursive`
3. submodules `https://github.com/citra-emu/dynarmic-android` and `https://github.com/MerryMage/ext-boost/` are not available. 

**Expected behavior**
Submodules loaded fully. 

**Screenshots**
![image](https://github.com/EKA2L1/EKA2L1/assets/11456035/628287a8-1d84-4910-94b4-45ae06c9967d)

**Your PC or smartphone specs**
- Ubuntu 22.04.4 LTS
- Intel Core i7-9850H 2.60 GHz
- Intel UHD Graphics 630

**Your emulator configuration**
- N/A

**Log**
- N/A

**Comment by pent0** [comment]
The first repository is unused, the second is still needed. I will migrate to mirror when I am available. You must wait more or you can open a pull request if you would like to help, I would appreciate it. Thank you.

**Comment by roma-jam** [comment]
@pent0 thanks for the response. 
Yep, I can do that. 

Which mirror can be used?

**Comment by pent0** [comment]
I think [this one](https://github.com/yuzu-mirror/ext-boost) can be used. Thanks a lot!

**Comment by roma-jam** [comment]
@pent0 PTAL: https://github.com/EKA2L1/EKA2L1/pull/529
