### ISSUE TITLE
Blank screen on Snapdragon when starting game

### ISSUE THREAD

**Issue by andiweli** [EKA2L1/EKA2L1#528]
**Describe the bug**
Empty screen when starting games on Snapdragon/Adreno (was working on my slower older Mediatek device)

**Your PC or smartphone specs**
- Android 11
- Snapdragon 720G
- Adreno 618

**Your emulator configuration**
- N-Gage QD RH-29

**Log**
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/14655726/EKA2L1.log)

**Comment by pent0** [comment]
Hi, I need more information.

Please save log through the three dots menu (...) after you exit the game and sends both android.log eka2l1.log and eka2l1_takethis.log.

In addition, please provide if this happens to all games or a specific game you run. It might be related to how the game is setup or works. Thanks.

**Comment by andiweli** [comment]
Hi!
Find everything attached.
It happens to all games tested... around 10.

[android.log](https://github.com/EKA2L1/EKA2L1/files/14666186/android.log)
[EKA2L1_TakeThis.log](https://github.com/EKA2L1/EKA2L1/files/14666187/EKA2L1_TakeThis.log)
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/14666188/EKA2L1.log)

**Comment by pent0** [comment]
Sorry, I still can't find why it happens through this log. One last try, if you can turn on Extensive logging option in .../General, then recapture the log as before, it would be great. If I can't still find out why through the log, I will find some other ways!

**Comment by andiweli** [comment]
> Sorry, I still can't find why it happens through this log. One last try, if you can turn on Extensive logging option in .../General, then recapture the log as before, it would be great. If I can't still find out why through the log, I will find some other ways!

Here we go...
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/14706732/EKA2L1.log)
[android.log](https://github.com/EKA2L1/EKA2L1/files/14706733/android.log)
[EKA2L1_TakeThis.log](https://github.com/EKA2L1/EKA2L1/files/14706734/EKA2L1_TakeThis.log)

It's this device...
https://www.xbox.com/en-US/cloud-gaming/logitech-g-cloud-gaming-handheld

Before I had this one, where your N-Gage Magic worked :)
https://anbernic.com/products/rg405m

**Comment by pent0** [comment]
It's very weird, I expect GLES errors but It never appeared in the log. Right now I can't code, but when I can I will send you debug build that will log out many more info for me. Very sorry, you might need to wait a while.

**Comment by andiweli** [comment]
No problem. Thanks for the great work!

**Comment by andiweli** [comment]
@pent0 quick update:

I only tested with the latest 0.1.0 version. But never with 0.0.9

The later one works!
So there seems to be something different between them.

**Comment by andiweli** [comment]
@pent0 again update:

Seems to be my fault with a special setting: Realtime accuracy

I set it to High on my Anbernic device. So I did on the newer Logitech Android device. 

On Anbernic it works. On Logitech it results in a black screen. 

So I set it to Low which seems to work 😂

**Comment by pent0** [comment]
Oh, it's been so long since people touched that option. Guess it broke along the way. Thank you for the tip! If it's all ok I hope we can close this. The accuracy can be dealed with later.
