### ISSUE TITLE
Add support for launching individual games from a frontend on Android

### ISSUE THREAD

**Issue by leonstyhre** [EKA2L1/EKA2L1#533]
Hi!

I have added support for EKA2L1 to the Android port of my ES-DE frontend (https://es-de.org) but there seems to be no way to launch individual games.

Could you perhaps look into adding this, so that EKA2L1 could be integrated with frontends as is possible already on desktop operating systems?

At the moment when launching a game from ES-DE it simply opens EKA2L1 and the user has to manually select the game to run from inside the emulator.

Thanks!

**Comment by pent0** [comment]
You can check #514 , emulator will export game launch parameter as json file. This json file can be passed as data URI so the emulator will launch game right away

**Comment by leonstyhre** [comment]
Thanks but it's not really a good solution, would it instead be possible to pass extras when launching the EKA2L1 activity? This way it would work the same as on the other platforms.

I use the `--device` and `--run` command line options on other platforms, and if these could be implemented as extras on Android it will work in an identical manner. Thanks!

**Comment by pent0** [comment]
Can I ask how exactly are you handling eka2l1. I understand this emulator
is stand-out in its launch method, which game are installed and not an
individual game ROM file. That is why the JSON method is up, exporting the
game as a pretended ROM file and reduces the complexity layer of having
users entering the game name and device code to the frontend manually. I
think entering these parameters are a toture especially on Android. I can
also port the JSON thing to PC if its needed.

I can still expose the arguments, but I just want to ask your method of
doing it.

**Comment by leonstyhre** [comment]
Hi, sorry for the really, really late reply. I've now added support for launching JSON files from ES-DE and it works perfectly fine, so I'll go ahead and close this issue!
