### ISSUE TITLE
List games apps

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#65]
Apps usually that display on Symbian main menu, is actually queries by the Akn framework server.

On the first run of the server, on each drive, the folder <drive>:/resource/apps are scanned for *.rsc files. The RSC file will have multiple resource data, which will describes the app infos.

There are two sections and two things we need to mark down here:
Icon:
- [x] AppList parser
- MIF file loading
  - [ ] Detect MIF type (SVG or MBM ?)
- [ ] SVG rasterizer
- [ ] MBM parser

**Comment by pent0** [comment]
Reference:
https://github.com/SymbianSource/oss.FCL.sf.mw.appsupport/blob/3efd2b6c5ad920873846770a70f9769721e494c8/appfw/apparchitecture/aplist/aplappinforeader.cpp

**Comment by williamsthing** [comment]
Sounds good, want me to work on this?

**Comment by Hamza417** [comment]
> Sounds good, want me to work on this?

Yeahh

**Comment by pent0** [comment]
Oops, sorry, already finished long ago!
