### ISSUE TITLE
Is this Symbian emulator for android

### ISSUE THREAD

**Issue by dhanial** [EKA2L1/EKA2L1#69]
Sorry for asking out of topic, is this symbian emulator for android ?

**Comment by pent0** [comment]
Nope, not now, sorry

**Comment by dhanial** [comment]
Do you have future plan to making for android too

**Comment by pent0** [comment]
I think i will, but we have to get this emulator to a stable state first.

**Comment by dhanial** [comment]
Thanks for the answer i'll be waiting for that miracle
