### ISSUE TITLE
SVG Tiny renderer

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#72]
Base works has been done, however, it's too much of a work for now:
- [ ] Binary SVG-Tiny renderer

- XML SVG-Tiny renderer
  * [x] Circle
  * [ ] Rectangle
  * [ ] Path
- [ ] GZIP decompressor

**Comment by ssine** [comment]
I think using an external SVG library like [this](https://github.com/igagis/svgren) may help.

**Comment by pent0** [comment]
Yeah, I think it would be great, but there is some problems adding up:
- A property binary SVG format by Nokia: I want to build the XML tree to
pass to the SVG renderer. I hope the library allows that.
- Hardware acclarated rendering: Cairo would do that, but it will create
another opengl context to render (if opengl is what it use). It would be
troublesome when using opengl.

I will still look on it anyway, thanks!

Vào 00:27, T.6, 20 Th12, 2019 sine <notifications@github.com> đã viết:

**Comment by pent0** [comment]
No need anymore
