### ISSUE TITLE
J2ME Support

### ISSUE THREAD

**Issue by vadosnaprimer** [EKA2L1/EKA2L1#76]
Symbian used to run j2me applications quite well (I tested it in Nokia's S60 SDK). Here's actual implementation of its Java Runtime:
https://github.com/SymbianSource/oss.FCL.sf.app.JRT

It's licensed as Eclipse Public License v1.0 (as seen in the source files), so it can't be just reused in a GPL project, but maybe it could be dynamically linked? Though I have no idea how to even build it.

But overall, is j2me support planned in the future? Emulation of this environment is really poor these days, the only emulator that supports most of it was KEmulator Lite, and it was bought out from its author and can't be developed. All others are broken to some degree. And there's no way to use emulator savestates in any of them. Yet there are lots of people interested in j2me, just no one with both _time_ and _skill_ :)

**Comment by pent0** [comment]
If you have Android, you can use [J2MELoader](https://github.com/nikita36078/J2ME-Loader) by @nikita36078. Perfect

There is a JRE in Symbian ROM and ROFS, I just need to specify the right argument to run. But I don't think it will be efficient (JIT in JIT). I will make it as a milestone anyway.

**Comment by vadosnaprimer** [comment]
There's also a [legal notice](https://github.com/SymbianSource/oss.FCL.sf.app.JRT/blob/master/legalnotice.txt), but it seems to talk about Sun Specifications and claiming they are met by the implementation. I don't remember if Nokia has met them (I've read that was why they never open-sourced JSR184). But I don't think it means it should be met by whoever uses Symbian's JRT - EPL **is** an open source license.

**Comment by vadosnaprimer** [comment]
> There is a JRE in Symbian ROM and ROFS, I just need to specify the right argument to run.

Do these look relevant?
https://github.com/SymbianSource/oss.FCL.sf.app.JRT/blob/0822c2dcfb807a245ec84ab06006b59df7aedab6/javaruntimes/standalone/src/javastarterimpl.cpp#L53

**Comment by pent0** [comment]
It may looks like so, but if you can find the source executable that exists on a real phone and calls this function, we can't launch it.
