### ISSUE TITLE
Softlock when Exit is pressed on template application (ITried)

### ISSUE THREAD

**Issue by childishbeat** [EKA2L1/EKA2L1#89]
When I "touch" the Exit option in ITried, whether it's under Options or not, the emulated system seemingly freezes (but not the rest of the emulator). Here's an example of logged details I got from running ITried: [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4214432/EKA2L1.log)

**Comment by pent0** [comment]
Noticeable things:

> E { eka2l1::view_session::fetch: Unimplemented view session opcode 19 }
> T { eka2l1::epoc::DebugPrint: Handling command 3009 for UI }
> C { eka2l1::epoc::LeaveStart: Leave started! Guess leave code: -1003 }
