### ISSUE TITLE
Softlock when certain buttons are pressed on template application (ITried)

### ISSUE THREAD

**Issue by childishbeat** [EKA2L1/EKA2L1#95]
When I press certain buttons in ITried, the emulator softlocks. Here are the logs I got from each one:
1. **Message** - [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4215244/EKA2L1.log)
2. **Message from file** - [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4215183/EKA2L1.log)
3. **Help** - [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4215103/EKA2L1.log)
4. **About** - [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4214978/EKA2L1.log)
5. **Exit** - [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4214432/EKA2L1.log)

This line of text in the logs of my tests with Help and About interests me and might interest you because while you told me to please declare any references of the text libgles_cm or libgles, I think it might or might not also have something to do with OpenGL: E { eka2l1::drivers::ogl_graphics_driver::run: Corrupted graphics command list! Emulation halt. }

**Comment by pent0** [comment]
Noticeable things:

> E { eka2l1::view_session::fetch: Unimplemented view session opcode 19 }
> T { eka2l1::epoc::DebugPrint: Handling command 3009 for UI }
> C { eka2l1::epoc::LeaveStart: Leave started! Guess leave code: -1003 }

**Comment by pent0** [comment]
1. and 2. should be fixed with #97 . Hope you can test them.
