### ISSUE TITLE
EKA2L1 crashes shortly after finishing loading Template application (ITried)

### ISSUE THREAD

**Issue by childishbeat** [EKA2L1/EKA2L1#98]
EKA2L1 crashes shortly after ITried has finished loading. Sometimes, an access violation message pops up shortly before the program closes as a result of the crash. However, if I try to "touch" the screen at the right time, I can successfully "touch" the screen before ITried crashes.
**Update**: Here's an example log that features the problem: [EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/4223987/EKA2L1.log)

**Comment by pent0** [comment]
This is fixed long time ago! Sorry
